elanthia-online/scripts

- scripts/diskus.lic
A simple script that I use to cast disks for people.
> Adds ;diskus script to cast disks on people if they don't have one

- scripts/diskus.lic
Previously this was just failing when trying to cast and moving on to the next person.
I tried to push this tiny change directly to master, but I get rejected when I try to push to master or a new remote branch:
```
ERROR: Permission to elanthia-online/scripts.git denied to sandersch.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
I verified that I am in the org, but looks like @ondreian and @mrhoribu are Owners while I am a Member and may have different perms.
> diskus: Wait for mana before trying to cast

- scripts/rofl-puzzles.lic
Usage:
`;rofl-puzzles <puzzle name>`
where `<puzzle name>` is one of the following:
auto       automatically solve puzzles when they appear (default behavior)
statue     move some some statues around on an altar
mosaic     find the right gem and symbol to put into the mosaic
crystal    choose the correct damage type to destroy monster paintings
stars      select the correct constellation to place in the night sky
ghost      use a wand to do stuff to a ghost
scramble   guess the word from scrambled letters
symbol     paint an Arkati symbol the correct colors and assemble
box        get some stuff from a box and do some things
candle     light the correct candle
contributions/thanks:
* Alastir for creating `;RoL` to answer trivia questions and providing solutions to many anagrams and the …
> Initial version of ;rofl-puzzles.lic

- scripts/bigshot.lic
Added option to flee from webs as well as added 917 to not stance offensive when using incant option
> Added new flee option

- scripts/bigshot.lic
updated the regex for cmd_spell to have cold in it for the extra variable tag. incremented bigshot version accordingly.
> added cold as an element type

- util/repo
add xml to file extensions that repo recognizes
> update repo - xml files

- .gitignore
- .travis.yml
- Gemfile
- scripts/rofl-puzzles.lic
- spec/rofl-puzzles/statue_spec.rb
This updates the Travis config to run rspec as part of the build. I moved the existing `util/repo` script to the deploy step and changed the script step to run rspec. I also included a spec I had already written to make sure everything is wired up correctly.
@ondreian what is the best way to test the Travis config? I was going to turn on PR builds, but I think that would run `util/repo` and publish all in flight PRs which is no bueno.
> Run spec in Travis CI

- scripts/bigshot.lic
-Fix ;bigshot bounty
-Don't flee from your own group even if they're not hunting
> Update bigshot to 3.75.

- scripts/bigshot.lic
updated logic to respect spell-list.xml STANCE setting so that it stance/dances accordingly to predetermined XML settings.
> fix INCANT attack command

- scripts/jbook.lic
jbook.lic was created due to some books/journals/etc in-game not having the ability to move to a specific page within them.
jbook allows for a player to change to any page available in a book given the page.
See the help from the script for more details.
> Add jbook.lic

- scripts/proctor.lic
> [proctor.lic] first draft of StringProc util;

- scripts/puritan.lic
the line after `improves somewhat` should be what we attempt to match
> [puritan.lic] better matching of 1004 outcome

- scripts/puritan.lic
1. blacklist mother-of-pearl
2. add upper limit for purify_gem recursion
3. handle misfires case better
4. handle race condition in container parsing on startup
> general fixes;

- spec/gameobj-data/skin_spec.rb
- type_data/migrations/3_rollout_fixes.rb
closes 87; 
closes 90; 
closes 91;
> general post rollout fixes for game obj data

- spec/gameobj-data/aggressive_npc_spec.rb
- spec/gameobj-data/alchemy_spec.rb
- spec/gameobj-data/boxes_and_picking_spec.rb
- spec/gameobj-data/ebon_gate_2016_spec.rb
- spec/gameobj-data/gem_spec.rb
- spec/gameobj-data/herb_spec.rb
- spec/gameobj-data/junk_spec.rb
- spec/gameobj-data/magic_spec.rb
- spec/gameobj-data/skin_spec.rb
- type_data/migrations/5_data_consistency_fixes.rb
- type_data/migrations/6_lm_trap_sellable_info.rb
- type_data/tables/armor.yaml
Fixes all known data issues previously memorialized in the specs.
> gameobj-data: Fix pending specs

- type_data/migrations/7_sos.rb
> add SoS definitions;

- spec/gameobj-data/skin_spec.rb
- type_data/migrations/10_gh_105_additional_skins.rb
Attempt to create/modify gameobj for issue #105
> gameobj: Fix additional skin related issues

- spec/gameobj-data/skin_spec.rb
- type_data/migrations/11_gh_106_ambergris_as_skin.rb
migration file to add black and grey ambergris to TYPE skin. Both already listed under TYPE furrier. See issue #106
> gameobj: ambergris as TYPE skin

- Guardfile
- spec/gameobj-data/armor_spec.rb
- spec/gameobj-data/clothing_spec.rb
- spec/gameobj-data/jewelry_spec.rb
- type_data/migrations/12_gh_97_xmlpatch_clothing_and_armor_exclusions.rb
Adds some exclusions that have been in xmlpatch for a long time.
> gameobj: armor and clothing exclusions from xmlpatch

- spec/gameobj-data/skin_spec.rb
- type_data/migrations/15_gh_119_thurfels_keep_skins_and_more_antler_types.rb
Adds missing entries from skin/furrier from #119
> gameobj: adds more variations for skins with varying descriptions

- spec/gameobj-data/aggressive_npc_spec.rb
- type_data/migrations/19_gh_125_bay_centaur.rb
> add bay centaur

- scripts/rofl-trivia.lic
Automatically answers Rings of Lumnis trivia questions
> rofl-trivia: Automatically answers Rings of Lumnis trivia questions

- scripts/rofl-questions.lic
> rofl-questions: support Arkati or lesser spirit forms of Zelia question

- spec/gameobj-data/skin_spec.rb
- type_data/migrations/22_zul_logoth_skins.rb
> gameobj: add leathery bat wing as a skin

- spec/gameobj-data/skin_spec.rb
- type_data/migrations/7_sos.rb
fix for #146 issue adding sidewinder scale to type SKIN and FURRIER
> update 7_sos for sidewinder scale

- scripts/traffle.lic
> feat: use --d --h --m --s format for more readable remaining time

- spec/gameobj-data/skin_spec.rb
- type_data/migrations/9_skin_fixes.rb
> Brown boars have hides not skins

- scripts/treim.lic
• Removing "closed" from the incant 435 routine due to issues
• Adding an additional mstrike after a 435 cast with no rare to help with cleanup
> Treim Scrub Update

- scripts/jbackup.lic
Adding new script for backup of some lich related configuration files.
> New Script: jbackup 

- scripts/jbackup.lic
> Updates to jbackup.lic to 0.0.2

- scripts/jbackup.lic
- scripts/jbook.lic
> Various Updates

- scripts/jbackup.lic
Added detection for invdb.lic.
If it exists then inv.db3 is also backed up.
> Added invdb Detection

- scripts/jbackup.lic
Changed invdb.lic detection to Scripts.exists?
Added ability to add, remove, & list files to backup.
> Added New Abilities

- scripts/jbackup.lic
New backups from this version on will be in a jbackup folder and date/time labeled subfolders.
> Backup Location Change

- scripts/treim.lic
- Added a new "badass" routine for bards that can cast and use mstrike
- Modified the "scrub" routine to check for offensive stance before mstriking
> Adding a new routine for hybrid bards

- scripts/tdig.lic
Modifying the seashell bundle routine to redeem seashells instead
> Update to handle seashells with no bucket

- scripts/traffle.lic
TownCrier API additions that should not impact anyone else.
Per @rsecor original PR #183
> Update traffle with API

- scripts/tfish.lic
- Handling an issue where you attempt to GO PATHWAY but are prone, causing the script to exit
- Modifying the knife functionality to specify a specific container for the knife (variables: fillet_knife and knife_container)
> Update for tfish

- spec/gameobj-data/ebon_gate_2016_spec.rb
- spec/gameobj-data/jewelry_spec.rb
- spec/gameobj-data/magic_spec.rb
- type_data/migrations/14_additional_jewelry_nouns_from_xmlpatch.rb
- type_data/migrations/26_ebon_gate.rb
gameobj-data.xml updates from Ebon Gate 2019
> gameobj-data: Ebon Gate 2019 updates

- scripts/reimmessage.lic
Removing Tysong and Siierra; replacing with Nodyre and Melivn
> Update to reimmessage for officer updates

- scripts/reimmessage.lic
- Updated to add support for Speed Run Fridays
- Updated to clarify our loot split instructions
TODO: Need to figure out how to add three new HALL EVENT EXECUTE actions
> Update to reimmessage.lic

- scripts/reimmessage.lic
Broken elsif statements in reimmessage
I suck
> Fixed an issue

- scripts/treim.lic
Added a paladin routine called "dredd"
> Updated for treim

- scripts/treim.lic
Updating PHYSICAL routine to use focused mstrike on bosses
This is to help alleviate issues with EBP for melee folks
> Treim Update for Melee

- scripts/tdusk.lic
Adding a tonis bard routine for Dayzed to cast 1005 then attack repeatedly
> Update for tdusk

- scripts/tdusk.lic
Update to Nodyre/Dayzed routines, some group arena logic, and some song of power logic
> Update to tdusk

- .travis.yml
- bin/verify_syntax
Had this lying around on my localhost, thought I'd clean it up for y'all to use.
> chore(ci): add syntax verifier prior to deploy;

- scripts/tdusk.lic
Adding routine for Kalcawkk
Small fixes for Dayzed/Nodyre
> Tdusk update

- scripts/tdusk.lic
Removing the extraneous waitrt? as recommended by Tysong
> Another tdusk update

- scripts/bigshot.lic
Received GTK-critical error when running on Fedora and corrected the errors by cleaning up mislabeled variables
> Corrected Block in Setup error

- scripts/tdusk.lic
Updates tdusk to add my characters with some custom routines.
> tdusk: add routines for Kragdruk's characters

- scripts/bigshot.lic
- Added overkill option for post-fried additional kills
- Changed formatting to be more easily read and standardized
- Added some tooltips
- Added more clarified error messaging
> Bigshot v3.8.7 Update

- scripts/bigshot.lic
v3.88 (2020-03-28)
-Fixed a bug with obvious_hiding_player detection (Probably, at least)
-Fixed a bug with poaching when other players are present
-Cleaned out changelog history after updating wiki
-Re-organized global variables and requires statements (alphabetized)
-Added a sleep between resting_commands and hunting_prep_commands to prevent issues
-Replaced all pause commands with sleep
-Updated all sleep commands to follow proper syntax
> v3.88 (2020-03-28) -> Bug Fixes and House Cleaning

- scripts/bigshot.lic
- type_data/migrations/27_update_sacristan_spirit.rb
- type_data/tables/passive_npc.yaml
- type_data/tables/undead.yaml
I can't do anything about TravisCI not working because of some non-existent new line that I can't reproduce
> Updated Sacristan Spirits

- scripts/treim.lic
> Treim Update for our Ranger Pals

- scripts/rofl-puzzles.lic
Fixes #229 
@rsecor are you able to test this branch?
> rofl-puzzles: work around NOMARKEDDROP setting

- scripts/treim.lic
- Added stance_dance checks to all calls to put stance offensive for melee. This will allow folks to stance down without the script forcing them back up
- Added MSTRIKE SET FOCUS value of 2 on active treiming to limit damage to rares (could love some code review on this for feedback)
> Updating treim to better handle melee

- scripts/disarmed.lic
Added empty_hands/fill_hands to the routine so that melee&shield/TWC users can use script.
> disarmed 1.4

- scripts/treim.lic
Adding "attack" routine to save on blessings
Breaking out 709 into it's own elsif block
Adding a 2 second pause for 1030/435/635
> Treim updates

- scripts/bigshot.lic
fix for archery update, commented out ammo getting
> bigshot v3.89

- scripts/bigshot.lic
Minor fix to add a delay to 130/sym of return/1020 return option case in RT
> update bigshot v3.90

- scripts/treim.lic
Lots of changes...
Added new routines
Removed FURY routine
Removed mstrike_limit variable and code
Modified existing routines
> Treim Update

- scripts/tears.lic
Added total cost estimates to calc function
> Update tears v1.3

- scripts/treim.lic
- Added "Cease fire" and "Resume fire" support
- Eliminated echoes and back-whispers for these conditions
- Suggest we deprecate the pause/resume attack support in a future version
> Adding an alternative Pause/Resume option

- scripts/bigshot.lic
Added option to have bigshot automatically use LTE boosts if defined
> Added LTE Boost option

- scripts/coin4deed.lic
A coin4deed script with an updated formula that works accurately!
> Created coin4deed.lic

- scripts/commas.lic
> fix(commas.lic): handle collisions with useherbs; do not modify id strings

- deepthoughts.lic
Takes ESP and pushes it to the speech window
> Adding deepthoughts script

- scripts/poolparty.lic
checked with glaves he's ok with moving this to elanthia online support
this is the exact 2.01 version (latest i had available) with the only change being removing glaves' contact info from the info section (as per his request)
a popular script, didn't want someone squatting on the name to troll people.
> import ;poolparty with permission from orginal author

- scripts/tdusk.lic
1.18 (2020-08-16) - Slight update for attacksript/bigshot users to not get stuck and better optimize round checking/finish for them. Change GameObj.npcs references to GameObj.targets
> tdusk v1.18 update

- scripts/tdusk.lic
v1.20 - Force killing of duskattack scripts if still running at end of arena.
> update tdusk v1.20

- scripts/tdusk.lic
Fix for crashing if you don't automatically start LNet/0Net on login.
> update tdusk v1.21

- scripts/healbot_actions.lic
- scripts/healbot_core.lic
Automated healbot script used in Shattered - available for others to view / recommend updates
> Initial commit of healbot_core and healbot_actions

- scripts/uhaul.lic
Uhaul patch for Kraken's Fall and Cysaegir.  Removes need for trust and backs out ostruct .
> Uhaul patch for Kraken's Fall and Cysaegir

- scripts/poolparty.lic
INFO was updated to return commas
might have broken several scripts.
> fixed commas in pool party

- scripts/oleani-lib.lic
- scripts/poolparty.lic
- scripts/slop-lib.lic
First push of oleani and slop to elanthia online.
PoolParty: Now tries to deposit boxes in your hands first
PoolParty: Uses Foreach's ItemMatcher class, which should fix not seeing boxes
PoolParty: General code cleanup.
> Updated poolparty and supporting libraries

- scripts/puritan.lic
> feat(puritan.lic): add round & shatter tracking;

- scripts/poolparty.lic
Fixes poolparty not waiting for your disk at the locksmith pool.
> Fixed Poolparty deposit disk wait

- scripts/tdig.lic
EMPTY won't grab species from the digging chests
Adding "species" to the uncollectibles array should do the trick.
Redeeming seashells after grabbing them
Fixing coin commas
> Fixes for tdig

- scripts/tgames.lic
Bank teller messaging updates and fixed small timing issue for tgames.lic
> Bank teller messaging updates and fixed small timing issue

- spec/gameobj-data/aggressive_npc_spec.rb
- type_data/migrations/35_eg_arena_of_the_abyss.rb
* add "multi-headed rotting chimera"
* explicit test case for "nonomino"
* add "wispy phantasm" as a base NPC description and remove boon tag
> gameobj: tweaks for AotA creatures

- scripts/tfish.lic
Fixes for lure descriptions and other things, credit to Ziled
> Update tfish v1.3

- scripts/tfish.lic
Added some cleanup when killing script to store supplies
> Update tfish 1.4

- scripts/tgames.lic
Add Teras bank teller messaging
> update tgames v1.9

- scripts/tdig.lic
Fixed empty logic for full container and deposit coins if encumbered.
> update tdig v1.12

- scripts/tdig.lic
Fixed empty container logic to not match on someone else's EMPTY messaging.
> update tdig v1.13

- scripts/tdig.lic
Added option to announce T5/jackpots to an ESP channel. Off by default.
> update tdig v1.14

- scripts/experfect.lic
ensure Opts & Log are not used unless defined.
> feat(experfect.lic): add gem installer

- scripts/asexualfavors.lic
- scripts/milkman.lic
- scripts/oleani-lib.lic
- scripts/poolparty.lic
Oleani-lib has been revamped from the ground up to help with scoping. 
All scripts that I've written now use the updated Oleani
Poolparty has been updated to address some issues that have been reported.
Asexualfavors and Milkman are being transferred to you.
Asexualfavors is the rewrite of sexualfavors that uses the resource command.
Milkman is a utility for unifying the display of LNET and ESP
> Updates to Poolparty/Oleani-lib and transfer of Asexualfavors/Milkman

- scripts/poolparty.lic
minor typo fix for Oleani::Support constant
> poolparty 2.08

- scripts/oleani-lib.lic
- scripts/poolparty.lic
Poolparty namespace was missing on the options rescue.
Internally Oleani had a few invalid method calls that testing had missed.
Updated both build numbers
> Updated poolparty & oleani-lib

- scripts/poolparty.lic
Added code to better handle odd boxes.
Fixed typo in the root rescue
Corrected lingering helper method signature
Updated build number
> Updated poolparty with fixes for odd boxes

- scripts/isquelch.lic
This adds a script which provides a configurable regex based scripting filter for incoming strings.
> Add first cut of isquelch script.

- scripts/isquelch.lic
This PR cleans up the isquelch script, largely by applying/satisfying [RuboCop](https://rubocop.org/).
> Clean up isquelch based on rubocop.

- scripts/isquelch.lic
Following the suggestion in #329, fix defining the instance variable used to look up script configuration.
> Fix instance variable declaration.

- scripts/cake.lic
Simple script that makes it easy to choose a particular type of manna bread and stick with it.
> Add cake.lic for controlling manna summons.

- bin/publish_jinx_repo
- scripts/jinx.lic
adds publishing script for Jinx package manager
> jinx publishing task

- scripts/jinx.lic
- spec/jinx/jinx_spec.rb
> feat(jinx.lic): script search command;

- scripts/resource.lic
> resource v1.0

- scripts/resource.lic
> resource.lic: fix PF in combined bonus lines for monks

- scripts/jinx.lic
- spec/jinx/jinx_spec.rb
Did some minor refactoring and was able to get the data list/install/update commands working. info seems like it would do the right thing if the metadata fields from the headers were there. I still need to update the usage info and implement the search command.
> jinx: data CLI

- scripts/jinx.lic
- spec/jinx/jinx_spec.rb
> jinx: noop if local file digest matches manifest

- scripts/bigshot.lic
Fixed stand() def to not stand if xbow kneel/firewhat
> Update bigshot 4.2.1

- scripts/bigshot.lic
Fix for certain values getting set when opening GUI, overwriting own settings
> bigshot v4.2.2

- scripts/coin4deed.lic
- Updated for commageddon fixes
- Cleaned up downstream hook
- Added ability to run five or 10 times consecutively
- Additional code cleanup
> Coin4deed v 1.1.0

- scripts/bigshot.lic
Fix cast roundtime regex match for change_stance def
> Update bigshot.lic v4.2.4

- scripts/poolparty.lic
icemule updated (again) npc name is apparently trickster
> [poolparty] add trickster to list of boxpool names

- spec/gameobj-data/passive_npc_spec.rb
- type_data/migrations/17_spirits.rb
Adds some more exceptions for spirit servants that I have run into.
> gameobj: add more spirit servant exceptions

- scripts/treim.lic
Add UserVars.treim[:script_args] to launch spam_scripts or activescripts with arguments
> Update treim.lic 2.23.1

- scripts/rofl-puzzles.lic
- scripts/rofl-questions.lic
Adds the questions from the Planar path to rofl-questions. Updates rofl-puzzles to deal with some slight changes this year to some of the puzzles and fix some places it might get hung up in unusual circumstances.
> Update Rings of Lumnis scripts for Planar path and 2021 changes

- scripts/rofl-puzzles.lic
Professional Goblets and Emotional Flowers
> rofl-puzzles: Added elemental puzzles

- scripts/bigshot.lic
Add flee from boon/boss/glamour mobs checkbox on attacking tab
> Update bigshot v4.3.0

- scripts/rofl-puzzles.lic
(begonia seeds were missing from the commented list of seeds)
> Add some Elemental seed puzzle translations

- scripts/rofl-questions.lic
> Add some Elemental questions

- scripts/rofl-notes.lic
A short script for auto bundling notes acquired through running Rings of Lumnis
> rofl-notes: Initial Creation

- scripts/bigshot.lic
Added regex for stance changing when using STANCE VERBOSE
> Bigshot 4.3.1

- scripts/rofl-questions.lic
> Add more elemental questions

- scripts/rofl-puzzles.lic
> Add some flowers and goblets

- scripts/hud_bounty.lic
migration of hud_bounty.lic to EO repository with a few minor fixes
> hud_bounty v0.3

- scripts/bigshot.lic
Revise GTK3 check to be more compatible with older versions of GTK that don't support Gtk::Version calls
> bigshot v4.3.3

- scripts/experfect.lic
- feat: add support for new field exp field;
- fix(experfect.lic): handle that they changed the format again;
> feat(experfect.lic): handle newest format of exp command;

- spec/gameobj-data/skin_spec.rb
- type_data/migrations/34_kf_herbs.rb
> gameobj: KF skin was added to skins but not furrier sellable

- scripts/jinx.lic
- spec/jinx/jinx_spec.rb
- spec/jinx/repos/mirror/assets/sloot.lic
- spec/jinx/repos/mirror/headers/sloot.header
- spec/jinx/repos/mirror/manifest.json
Updates the default seeded repos. Add's @FarFigNewGut's repo for everyone and the gtk3 script updates repo if the Gtk3 constant is installed.
> jinx: adds FFNG's mirror and gtk3 repo seeds

- scripts/bigshot.lic
Add flee from voids option to general tab
> bigshot v4.4.0

- scripts/bigshot.lic
Add fog only if encumbered or injured checkbox
> Update bigshot.lic 4.5.0

- scripts/update-lich5.lic
Script to update Lich 5.0x to current 5.14 and for future updates until a more long-term update mechanism can be developed.
> Update Lich-5 script from Doug

- scripts/update-lich5.lic
Updates from Doug for post PSM3 to support 5.0.16
> Update to the update-lich5 script to support 5.0.16

- spec/gameobj-data/duskruin_spec.rb
- type_data/migrations/41_duskruin_items.rb
The misericord showing up as a weapon was really annoying me.
> gameobj: add event:duskruin type to Duskruin-specific item drops

- scripts/lich5-update.lic
Craete file to support lich5-update
> Create lich5-update process

- scripts/resource.lic
Non-warrior using ;resource bonus warrior
```
Grit (WPS) Success Formula
---------------------------
100 : Level
+  30 : STR Bonus
+  25 : DIS Bonus
+  30 : Physical Fitness
+  20 : Workshop Bonus
+ Primary Skills:
Weapons (specific to weapon type being serviced):
303 : Two-Handed Weapons
303 : Brawling Weapons
Armor (only applies to armor and armor accessories):
106 : Armor Use
+ Secondary Skills:
Weapons (specific to weapon type being serviced):
202 : Edged Weapons
202 : Blunt Weapons
101 : Two-Handed Weapons
202 : Ranged Weapons
202 : Thrown Weapons
202 : Polearm Weapons
101 : Brawling Weapons
Armor (only applies to armor and armor accessories):
0 : Shield Use
===========================
311 : Armor
407 : Edged Weapons
407 : Blunt Weapons
609 : Two-Handed Weapons
407 : Ranged Weapons …
```
> [resource.lic] add support for warrior Grit

- scripts/bigshot.lic
* Rebased 4.70 update to 4.61 base to include missing changes
* Supercedes PR #522
> 4.61 to 4.70

- type_data/migrations/9_skin_fixes.rb
another skin where the name is different on ground/containers vs in hand
> [game-obj] add mountain snowcat pelts

- scripts/ForgeMaster.lic
- scripts/MyFletch.lic
- scripts/armor.lic
- scripts/auto-level2.lic
- scripts/bardwag.lic
- scripts/betazzherb.lic
- scripts/boon.lic
- scripts/clearcheckwiz.lic
- scripts/cure.lic
- scripts/fletchit.lic
- scripts/fletchmaster.lic
- scripts/forgery.lic
- scripts/gsigils.lic
- scripts/hands_and_room.lic
- scripts/heal_spellup.lic
- scripts/iSigns.lic
- scripts/isigils.lic
- scripts/loot-be-gone.lic
- scripts/madwarrior.lic
- scripts/mechfire.lic
- scripts/mybounty.lic
- scripts/pt.lic
- scripts/signore.lic
- scripts/symbolz.lic
- scripts/uberfletch.lic
- scripts/waggle.lic
Merging files from GTK3 scripts into scripts
> Merging GTK3 scripts

- scripts/sloot.lic
Putting SLoot v 3.5 in place as SLoot, removing 2.0.2
> GTK3 SLoot v 3.5 to replace 2.0.2

- bin/repo
- scripts/jinx.lic
- fix: don't throw on remote repo exception;
- feat(jinx.lic): add repo pruning;
> jinx: add pruning of deprecated repos on startup

- scripts/bigshot.lic
Updated gui setup to cover gtk2, gtk3 dark mode and gtk3 normal mode.
Resolves #564
> Fixing GUI for gtk2, gkt3 both modes

- scripts/resource.lic
removes "proposed" from cleric and adds warrior to the header / readme section
adds more tags for cleric abilities
> [resource.lic] clarify header and add more tags

- scripts/wps.lic
They changed it from he to it then back again.
> wps: blacksmith changed pronouns again so updated to accept whatever

- scripts/tsquelch.lic
Rewrote majority of all REGEX matches to be less greedy, hopefuly meaning less ReDoS lag
> Update tsquelch v2.0

- scripts/resource.lic
think this is good?
error checked manually and against Maodan who had a similar update he dropped in discord
> [resource.lic] added druid fluid

- scripts/alchemy.lic
Update alchemy to support new exact MEASURE capabilities.
> Update alchemy.lic v0.21

- scripts/bigshot.lic
Added all active cman abilities. Not martial stances at this time.
Bearhug and Coup de Grace may need to add a command check for the buff. Not sure if it will over write surge or if the higher bonus sticks.
> added cmans in hopefully got them all.

- scripts/autostart.lic
- scripts/go2.lic
- scripts/infomon.lic
- scripts/lich5-update.lic
- scripts/lnet.lic
> Rebase with newer EO/Lich-5

- scripts/go2.lic
Replacing check_silvers DS hook with 5.4.0 command Lich::Util.silver_count
> Adding Lich::Util.silver_count to script to remove display error

- scripts/infomon.lic
Correcting regex for these two spells in infomon
> Correct spell numbers 712 / 520

- scripts/bigshot.lic
Yep 6 commits for 9 lines of code. Got to be a record right?
> mana pulse for 130 in fog situations

- scripts/spell-list.xml
update Arcane Mobility -> Martial Prowess and reflect correctly.
> Spelllist Update 1705

- scripts/spell-list.xml
Test push to EO/Lich-5 and adding changelog header to spell-list.xml
> Lich5 Push Test

- .github/workflows/publish-gameob.yaml
- .github/workflows/publish.yml
- .github/workflows/test.yml
Fix for libxml2-utils apt source needing update
> Update Workflows - apt-get repo sources

- scripts/waggle.lic
Replaced squelching of SPELL ACTIVE using Lich::Util.quiet_command_xml
> Update waggle.lic - squelch and lich version check

- scripts/spell-list.xml
1235 messaging update. Correctly adding update for spell-list.xml and remaking PR due to workflow changes that would cause failure for #571.
Closes #571
> Add 1235 messaging

- scripts/log.lic
Adding script to support DR and Lich5 transitions.  Unclear if this will populate to the repo automatically.
> Adding modified log script to support DR / LIch5

- scripts/eforgery.lic
Rename to eforgery from forgery for ease of distribution
Change versioning to semantic system
> Update and rename forgery.lic to eforgery.lic

- scripts/go2.lic
Update to version 1.32. Version 1.31 brings in DR changes. Version 1.32 brings in yaml-based map stringproc overrides for DR, which provide a structure for fixing Lich5 travel hiccups and for power users to set up their own stringprocs.
> [script][go2] - Bring in DR updates including DR map stringproc overrides

- scripts/eherbs.lic
> [eherbs.lic] LICH version check

- scripts/resource.lic
Added bonus calculations to now save on run(and update if changed)
Added the `all`/`characters` option to show all previously recorded bonuses.
> [resource.lic] add saving/display of bonuses

- spec/gameobj-data/skin_spec.rb
- type_data/migrations/44_missing_bundles.rb
> [gameobj] missing skin/furrier bundles

- type_data/migrations/44_missing_bundles.rb
Fix for drop of adjective for brindlecat hides.
> [gameobj] add brindlecat hide bundles

- scripts/bigshot.lic
Update consecrate to not return from hunt if blessing a sanctified weapon per #272
> [bigshot.lic] 1604 blessing bugfix

- scripts/treim.lic
Add option to start custom attack script (eg ;treim tysong-duskattack.lic)
> [treim.lic] custom attack script option

- scripts/eloot.lic
fixed the fix to the skinning fix
> [eloot.lic] skinning with empty skin variables fix

- scripts/eloot.lic
v1.2.6 (2022-04-15)
- support for weapon displayers
> [eloot.lic] weapon displayer support

- scripts/bigshot.lic
will track swift justice charges. (justice) do skill if have charges (!justice) do skill if don't have charges
Tysong's adjustment to hide command to specify attempts to try.
> [bigshot.lic] swift justice tracking and command check, hide attempt change

- scripts/autostart.lic
- scripts/version.lic
- scripts/xnarost.lic
Sync up with EO/Lich5 in prep for having scripts in single github repository
> [scripts] update Lich5 scripts to match

- scripts/eloot.lic
- scripts/eloot.ui
v1.2.7 (2022-04-21)
- removed redundant container looks
- additional looting bug fixes.
- fixed invalid loot bug
> [eloot.lic] various bug fixes and optimizations

- type_data/migrations/45_hinterwilds.rb
Added mastodon trunk and likely the exclusion for dropping part of the adjective descriptors.
> [45_hinterwilds.rb] additional gameobj-data from HW

- scripts/eloot.lic
fix inventory containers regex with full hands
> [eloot.lic] fix inventory containers regex

- scripts/infomon.lic
Fix for PSM info now having type column and truncating certain skills
> [infomon.lic] fix for PSM info output change

- type_data/migrations/44_missing_bundles.rb
- type_data/migrations/45_hinterwilds.rb
> [45_hinterwilds.rb] additional gem

- scripts/eloot.lic
- scripts/eloot.ui
> [eloot.lic] v1.3.0 bugfixes and exclusion loot/skin

- scripts/eloot.lic
- bugfix for not equiping hands after emptying during loot/skinning
- bugfix for not detecting proper storing of loot in container via try_or_fail
> [eloot.lic] bugfixes v1.3.1

- scripts/eloot.lic
- scripts/eloot.ui
v1.3.2
- fixed bug that prevented gold rings from being deposited with chronomage
- added check for trying to loot crumbly items
- added looting and disposing of food items -limited functionality due to so many food variations
> [eloot.lic] v1.3.2 bugfixes and updates

- type_data/migrations/45_hinterwilds.rb
Add a stygian valravn quill. Currently not sellable ANYWHERE but is a writable quill and is a super rare drop from Valravns.
> [gameobj] HW rare drops, unsellable

- scripts/eloot.lic
- scripts/eloot.ui
v1.3.3
- added support for sheaths
- added autostart support: ;autostart add eloot start
- added a check for berserk being active
- fixed skin bundler looting
> [eloot.lic] v1.3.3 various fixes

- scripts/eherbs.lic
Fix for gambling kit open/close/get/put regex.
fixes #732
> [eherbs.lic] v1.1.3 gambling kit support

- type_data/migrations/45_hinterwilds.rb
Add various hinterwild bosses and associated items.
> [gameobj] hinterwild bosses

- scripts/eloot.lic
- scripts/eloot.ui
Corrected some messaging in loot_bag method
> [eloot.lic] v1.3.4 bugfixes and cleanup

- type_data/migrations/47_forgotten-valley.rb
> [gameobj] Forgotten Valley

- scripts/eloot.lic
- scripts/eloot.ui
v1.3.5 (2022-05-24)
- removed tryin to phase a box in a disk, that doesn't work
> [eloot.lic] v1.3.5 fixs

- scripts/bigshot.lic
Update various GameObj.npcs to use GameObj.targets
> [bigshot.lic] v4.12.0 updates

- scripts/bigshot.lic
that caused you to flee when someone entered the room. The bug was introduced when trying to fix a bug with poaching in the first room of the hunt. Both bugs should be fixed.
> [bigshot.lic] adjusted hunt logic to squash bug

- scripts/spell-list.xml
Update various bonuses to be inline with current added benefits
> [spell-list.xml] fix bonuses

- scripts/eloot.lic
bug fix to recognize new crumbly items properly
> [eloot.lic] v1.3.7 bug fix

- scripts/bigshot.lic
Add checks for Divergence cooldown spells for hunting tab abilities/spells/cmans (140, 211, 215, 219, 240, 919, 1619)
> [bigshot.lic] v4.12.2 fixes

- scripts/go2.lic
Add a caravan to sos and from sos options
Fix for use-urchins not recognized in command line
> [go2.lic] v1.36.0 sos_caravan and bugfixes

- scripts/eloot.lic
added skin matching for alchemically ruined skins
> [eloot.lic] v1.4.4 fixes

- scripts/resource.lic
Initial attempt at adding rogue service stuff
> [resource.lic] 1.8.0 add rogue service

- scripts/eherbs.lic
Update (fixes #741 )
- Fixes counting herbs properly for stow function, and corrects stow function
- Fixes RR bombing because RR doesn't have rose-marrow on the menu
- Fixes 'list' ( ;eherbs list ) to properly display requested subtypes ( ;eherbs list minor or ;eherbs list minor nerve or ;eherbs list minor nerve scar )
- Adds feature 'blood' ( ;eherbs blood ) which ignores wounds and heals only hits
- Adds feature 'wound type for stock' ( ;eherbs major head wound ) to stock only that certain herb type
> Updates to eherbs to fix and add features

- scripts/spellactive.lic
add, delete, clear room numbers where magic is ineffective.
toggle for sigil of power, defaulted to on to maintain original functionality.
;spellactive help
If someone wants to make it autoadd nocast rooms, that would be cool too.
> [spellactive.lic] added support for nocast rooms

- scripts/bigshot.lic
from inside of def cmd() to def attack(target).
> [bigshot.lic] relocated troubadour's rally check

- scripts/bigshot.lic
removed delay
incapacitated yourself - shout 1040 until all better attempting mana pulse if needed.
group mate - will weave shout 1040 in between your hunting commands until mates are all better.
> [bigshot.lic] shout 1040 adjustments

- scripts/bigshot.lic
> [bigshot.lic] opt-out of mstrike on unarmed combat

- scripts/bigshot.lic
missed a spot it needed to be listed.
> [bigshot.lic] frozen fix

- scripts/eloot.lic
- scripts/eloot.ui
v1.4.11 (2022-08-02)
- added support for looting coins on the ground
> coin looting support

- scripts/echild.lic
- custom proc for Maaghara; 
- custom proc for Atoll; 
- added global $child_last_seen;
- removed final pause if not Drafix, etc.
- added test mode where you can sub an npc, like a familiar for testing --test:owl
- added check for being able to cast before running potentially unnecessary justice check
- moved into module, updated can_cast debuff list
> [echild.lic] various updates

- scripts/infomon.lic
Fix for spell cleanup for missing XML spells/buffs/etc
> [infomon.lic] v1.18.16 bugfix

- spec/gameobj-data/passive_npc_spec.rb
- type_data/migrations/17_spirits.rb
gameobj: exclude sacristan spirits (regular and grizzled versions) from spirit servants
> gameobj: exclude sacristan spirits (regular and grizzled versions) from spirit servants

- scripts/eloot.lic
comma comma comma commma comma chameleoonnnnnn
> [eloot.lic] quick typo fix for default_crumbly list

- type_data/migrations/13_use_names_not_nouns_for_loot_boxes.rb
add deeply scored without the dash.
> [gameobj] Boon box fix

- scripts/disarmed.lic
Update the author to elanthia-online and force refresh of `;repo` version.
> [disarmed.lic] update author

- scripts/CombatLog.lic
Cleaned it up a bit. Made it easier to expand. Added a few skills/flares.
> [Combatlog.lic] rewrites on rewrites

- type_data/migrations/27_weapons.rb
> [gameobj] add longbow weapon

- mapdupes.lic
script to help clean up duplicates from the map database
> [mapdupes.lic] initial creation

- scripts/eloot.lic
bugfix for terminal-table silver breakdown
> [eloot.lic] v1.5.1

- scripts/bigshot.lic
waitcastrt? unless command =~ /hide|cock/da  to waitcastrt? unless command =~ /hide|cock/
> [bigshot.lic] fixed typo

- scripts/resource.lic
Fix for updated GRIT formula changes
> [resource.lic] v1.8.2 Grit Updates

- scripts/resource.lic
> [resource.lic] update

- scripts/resource.lic
I thought it would be helpful to be able to keep track of characters available resource and suffusion values
> Added suffused, weekly and total resource values to the 'all' output

- scripts/bigshot.lic
v4.13.2 (2022-11-5)
- added support to designate a looter for head/tail operations: See Misc tab
- added check for ...wait issue on routines
- reorganized the commands a little more to help with troubleshooting
> [bigshot.lic] v4.13.2 fixes

- scripts/bigshot.lic
> [bigshot.lic] v4.13.5 MA looter fix

- type_data/migrations/50_moonsedge_crawling_shore.rb
Adding flickering mist-wreathed banshee to boon exclusion list
> [gameobj] Moonsedge Boon Exclusion

- type_data/migrations/51_rare_treasure.rb
Add small totem as a magic item and sellable at pawnshop
> [gameobj] rare treasure

- scripts/eloot.lic
v1.5.6 (2022-11-11)
- added an "Always Loot" list
- added support for auto closing bags
-bug fix for handling reliquaries
> [eloot.lic] v1.5.6 updates

- scripts/bigshot.lic
Fix to correct assignment instead of comparison for overkill hunting.
> [bigshot.lic] v4.13.7 overkill bugfix

- scripts/group.lic
convert to a CLASS to prevent namespace conflicts
> [group.lic] v3.2.0 change to class

- scripts/bigshot.lic
Convert directory lookups to File.join to prevent OS pathname issues
> [bigshot.lic] v4.13.8 update

- type_data/migrations/50_missing_valuables.rb
- type_data/migrations/52_missing_valuables.rb
Add missing valuables. Addresses #817
> [gameobj] missing valuables

- scripts/ebounty.lic
v1.0.1 (2022-11-26)
- hedgehog sack messaging
- fixed herb names
> [ebounty.lic] v1.0.1 bug fixes galore

- scripts/eherbs.lic
Fix to exit after setting change from CLI
> [eherbs.lic] v1.4.4 setting fixes

- scripts/xnarost.lic
> [scripts][xnarost]Remove reference to $SAFE 

- scripts/version.lic
> [scripts][version]Remove  references to $SAFE

- scripts/log.lic
Removing outmoded check for lich version too.
> [scripts][log]Remove  reference to $SAFE

- scripts/repository.lic
Also removed a couple leftover comments.
> [scripts][repository]Remove  reference to $SAFE

- scripts/lnet.lic
Gentle clean up. Tested, works. 
I don't know wtf the deal is with the spacing in the changelog. It's all consistent now at least.
> [scripts][lnet]Remove $SAFE reference 

- scripts/go2.lic
Moved some setting definitions around so DR would get the ones that exist there, and gating ones that don't exist behind a game check.
Also brought the custom wayto functions up to date with the current dr-scripts version.
> [scripts][go2] Adjusting for features that exist (and don't) in DR

- scripts/go2.lic
> [go2.lic] v2.0.5 bugfix

- scripts/resource.lic
Adjust enchanting calc silver rates to $3.50/$4.00 from $4/$5
> [resource.lic] v1.8.6 RL silver cost adjustment

- scripts/tags.lic
Version: 1.6.1 (2022-11-12): Xanlin: added 'ranger', 'outside', 'climate' options
Version: 1.6.0 (2022-11-05): Xanlin: now collects climate and terrain data if you're a ranger
Version: 1.5.0 (2022-11-04): Xanlin: now collects missing uids while crawling (more helpful for plat)
> [tags.lic] update

- scripts/bigshot.lic
bug fix for comparison of bonded weapon return
> [bigshot.lic] v4.13.10 comparison bug

- scripts/bigshot.lic
v4.13.11
- bounty mode will only exit if bounty is complete or child present
> [bigshot.lic] v4.13.11 bounty fix

- scripts/ebounty.lic
v1.0.4 (2022-11-30)
- bug fix on container opening
- adjusted hunting sequence due to bigshot bounty_eval changing
> [ebounty.lic] v1.0.4 more fixes

- scripts/bigshot.lic
v4.13.13 (2022-12-3)
- add bounty check while resting and in bounty mode
> [bigshot.lic] v4.13.13 bounty checks

- scripts/eloot.lic
v1.5.7 (2022-11-27)
- removed custom quiet command to use Lich command instead
> [eloot.lic] v1.5.7 code cleanup

- spec/gameobj-data/gem_spec.rb
- type_data/migrations/52_missing_valuables.rb
Change piece of rosespar from `valuable` to `gem`
> [gameobj] piece of rosespar

- scripts/eloot.lic
v1.5.8 (2022-12-05)
- added word boundary checks for container setup
> [eloot.lic] v1.5.8 container bugfix

- scripts/ebounty.lic
v1.0.10 (2022-12-11)
- fixed foraging herb matching bug
> [ebounty.lic] v1.0.10 forage fix

- scripts/eherbs.lic
1.4.5 (2022-12-11): Deysh: Added UI
> [eherbs.lic] v1.4.5 add GUI setup

- type_data/migrations/41_duskruin_items.rb
> [gameobj] duskruin items - stone

- scripts/ebounty.lic
v1.0.11 (2022-12-12)
- foraging name match fix
> [ebounty.lic] v1.0.11

- scripts/ebounty.lic
v1.0.12 (2022-12-15)
- made resting room a required parameter
- consolidated odd herb names
> [ebounty.lic] v1.0.12 resting_room and herb name fixes

- scripts/eherbs.lic
revert 1.4.4, restores override functionality for CLI options
> [eherbs.lic] update 1.4.6

- scripts/disarmed.lic
Add option to cast minor sanctuary/song of peace if known. Fixes and closes #659
> [disarmed.lic] v1.5.0 sanctuary option

- scripts/ebounty.lic
v1.0.13 (2022-12-19)
- add regex for opening an item
> ebounty.lic

- scripts/burstcalc.lic
Migrate script from Tysong to EO as owner.
> [burstcalc.lic] migration to EO

- scripts/spell-list.xml
Correct 709 to grasp of the grave and add 1714 quake
> [spell-list.xml] 709/1714 fix

- .github/workflows/test.yml
- scripts/spell-list.xml
Fix mana cost for 501 to be equivalent to Char.leve due to scaling mana costs. Change 218 to be stackable from refreshable
> [spell-list.xml] 501/218 Changes

- scripts/spell-list.xml
to mirror effects names so infomon stops removing them from ;magic.
> [spell-list.xml] Updated Aspect names

- scripts/infomon.lic
added exception for assume aspect cooldowns so infomon will track them properly.
> [Infomon.lic] Fix tracking for AA cooldowns

- scripts/spell-list.xml
Initial addition of some Major Mental and Savant base spells.
> [spell-list.xml] Add MjM and Sav spells

- scripts/treim.lic
Bug fix for using custom attack
> [treim.lic] v2.24.1

- scripts/spellactive.lic
> [spellactive.lic] fix version number

- scripts/bigshot.lic
bugfix for casting 1650 in cast_signs not working due to 650 regex
> [bigshot.lic] v1.13.14

- scripts/eloot.lic
> [eloot.lic] v1.5.11

- scripts/bigshot.lic
Add 1650 cooldown check for cast_signs
> [bigshot.lic] v4.13.15

- scripts/ebounty.lic
Change EBounty.data.location_start to use nearest instead of first in list
> [ebounty.lic] v1.0.22

- scripts/ebounty.lic
Fix badlist rooms and add bad logging road rooms
> [ebounty.lic] v1.0.25

- scripts/bigshot.lic
v4.13.16 (2023-01-21)
- added support to rest for debuffs: Wall of Thorn Poison, Confusion, Creeping Dread, and Crushing Dread
> [bigshot.lic] v4.13.16

- scripts/ecleanse.lic
v1.0.3 (2023-01-23)
- bug fix in recover weapon
> ecleanse.lic

- scripts/ebounty.lic
fix bugfix in variable list from v1.0.29
> [ebounty.lic] v1.0.29

- scripts/ebounty.lic
> [ebounty.lic] v1.0.30

- scripts/eherbs.lic
> [eherbs.lic] winterberry update

- scripts/CombatLog.lic
- scripts/bodega.lic
- scripts/cartograph.lic
- scripts/elogin.lic
- scripts/jbackup.lic
- scripts/jinx.lic
- scripts/lich5-update.lic
- scripts/log.lic
- scripts/orbuculum.lic
- scripts/repository.lic
- scripts/sammu.lic
- scripts/scripts.lic
- scripts/version.lic
- scripts/wannabe.lic
- scripts/xnarost.lic
Update for Ruby v3 compatibility
> [chore][multiple scripts]Add changelog/version for File.exist? updates

- scripts/tradingranks.lic
Change max ranks to 302 for enhancive & ascension possibilities
> [tradingranks.lic] v1.4

- type_data/migrations/40_fwi_npcs.rb
Fix petrified sprite figurine to be sellable at pawnshop and that it's valuable not magic #977
> [gameobj-data.xml] update FWI loot drop

- scripts/ebounty.lic
v1.0.31 (2023-01-24)
- reordered casting of song of peace during foraging and stopping it when done.
> [ebounty.lic] v1.0.31

- scripts/ecleanse.lic
v1.0.4 (2023-01-24)
- bug fix in remove stuff for barkskin check
- update 1011 casting so it doesn't repeat
> [ecleanse.lic] v1.0.4

- scripts/bigshot.lic
add new slayer command for 240
> [bigshot.lic] v4.14.0

- scripts/ebounty.lic
v1.0.32 (2023-01-26)
- bugfix for heirloom searching
> [ebounty.lic] v1.0.32

- scripts/spellactive.lic
Add check for cooldown for short duration buffs
> [spellactive.lic] v1.3.1

- scripts/infomon.lic
Fixed bad PSM evaluations on partial regex match (shield_strike bug)
> [infomon.lic] v1.18.19

- scripts/ebounty.lic
v1.1.1 (2023-02-01)
- bug fix for foraging spells (waitcastrt? for assume yierka)
- rearranged post-hunt sequence to mimic bigshot functionality. 
-fixed forage/heirloom search using empty_hands
> [Ebounty] post-hunt sequence change and empty_hands fix for forage/heirloom

- scripts/tradingranks.lic
Update for new racial purchase/selling chart
> [tradingranks.lic] v1.5

- scripts/tradingranks.lic
> [tradingranks.lic] v1.6

- scripts/bigshot.lic
added check to remove group members that made it into the room claim. fixed regex so attacks do not remove people from room claim.
> [bigshot.lic] quick fixes

- scripts/bigshot.lic
updated second target check to pull targets and validate instead of returning just because it's present.
> [bigshot.lic] v4.14.4 targetting updates

- scripts/resource.lic
Fix to include outside? bonus for ranger resistance to saved bonuses
> [resource.lic] v1.8.8 fix for Ranger bonus saving

- scripts/go2.lic
Added tags for treasuremaster, portmaster, cobbling, and grocer
> Update go2 with various tags

- scripts/ecleanse.lic
bug fix for incorrect method name during spirit servant recovery
> [ecleanse.lic] v1.0.8

- scripts/bigshot.lic
> [bigshot.lic] v4.15.0

- scripts/version.lic
Support for showing custom scripts
> [version.lic] v0.57 Support for showing custom scripts

- scripts/ledger.lic
> [ledger.lic] v1.1.1 mono fix

- type_data/migrations/45_hinterwilds.rb
> [gameobj-data] add oozelings to hinterwilds

- scripts/bigshot.lic
- initial bugfix(s) for Ruby 3.x compliance
- fix for exiting cmd_force if command check fails on cmd
> [bigshot.lic] v4.15.1 fixes

- scripts/echild.lic
Bugfix for Ruby v3.x compatibility
> [echild.lic] v1.18.8 Ruby v3.x compatibility

- scripts/bigshot.lic
> [bigshot] v4.15.3

- scripts/go2.lic
navigate out of a playershop even if it's not mapped (GS only)
> [go2.lic] update

- scripts/eloot.lic
bugfix for updating values that are nil for Ruby v3
> [eloot.lic] v1.5.22

- scripts/eherbs.lic
remove $infomon_cutthroat reference for cutthroat? reference.
> [eherbs.lic] v1.5.12 cutthroat? fix

- scripts/go2.lic
bugfix for integer comparison to string for Society.rank
> [go2.lic] v2.0.8 Ruby 3.2 fixes

- scripts/resource.lic
> [resource.lic] v1.8.9 rubocop cleanup

- scripts/jbackup.lic
Rubocop cleanup
Fix unnecessary creation of backup folders when running add, remove, init, list, reset, help commands
> [jbackup.lic] v0.2.3 fixes

- scripts/eboost.lic
Add supercharge messaging and updated header to be more accurate.
> [eboost.lic] v0.0.1-rc.3

- .rubocop.yml
- scripts/bigshot.lic
> [bigshot.lic] v4.15.5 rubocop cleanup

- scripts/repository.lic
Set GST to default update mapdb if not set to false/true already
> [repository.lic] v2.43 GST mapdb updatable default

- scripts/bigshot.lic
Add cman sbash to cmans as was missing
> [bigshot.lic] v4.15.6

- scripts/waggle.lic
Update wander proc for FalseClass error
> [waggle.lic] v0.18.4

- scripts/ewaggle.lic
Redo PR #675 and add bail option
> [ewaggle.lic] v1.0.0 from waggle v0.18.4

- scripts/ecure.lic
rebase cure.lic to ecure.lic and cleanup for Ruby 3.2 compatibility and rubocop
> [ecure.lic] v1.0.0 rebase cure.lic

- scripts/bigshot.lic
v4.16.0 (2023-04-06)
- Add bard command unravel to dispel and stop 
- Add bard command barddispel to dispel single spell from target
> [bigshot.lic] v4.16.0 new command options

- scripts/elogin.lic
Change from using SAL login method to native character saved entry CLI login method
> [elogin.lic] v1.1.2 CLI login change

- scripts/bigshot.lic
Update for GROUP output display
> [bigshot.lic] v4.16.2 GROUP output fix

- scripts/manaleech.lic
Fix for new GROUP output display
> [manaleech.lic] v2.7 GROUP output fix

- scripts/treim.lic
Fix for GROUP output update and Rubocop cleanup
> [treim.lic] v2.24.2 GROUP output update

- scripts/bigshot.lic
Update for groupcheck to strip XML from $grouplist
> [bigshot.lic] v4.16.3 groupcheck strip XML

- scripts/group.lic
Fix groupcheck for updated GROUP output display
> [group.lic] v3.2.1

- type_data/migrations/56_briskers_cove.rb
> [gameobj-data.xml] Updates for Brisker's Cove

- scripts/ewaggle.lic
Change eat to gobble method for 203
> [ewaggle.lic] for gobble in 203

- scripts/eforgery.lic
> [eforgery.lic] v1.0.4

- scripts/effect-list.xml
- scripts/jinx.lic
- scripts/repository.lic
Create new XML for conversion of spell-list.xml to gain ;repo ownership.
> [effect-list.xml] initial creation for ownership

- scripts/repository.lic
bugfix for script/Script scope
> [repository.lic] v2.45 bugfix for script/Script

- scripts/autostart.lic
Change Infomon::CLI.sync to proper Infomon.sync
> [autostart.lic] v0.58 Infomon.sync fix

- scripts/version.lic
Add effect-list.xml check and rubocop cleanup
> [version.lic] v0.58 effect-list compatibility

- scripts/linktothefast.lic
Migrate to EO ownership under game=gs to correct $SAFE issues.
> [linktothefast.lic] v0.1.5 EO migration

- scripts/eloot.lic
prep for new lich 5.7.0 infomon.lic change
> [eloot.lic] v1.5.33 infomon lib compatibility

- scripts/ebounty.lic
prep for new Lich 5.7.0 infomon.lic & effect-list.xml change
> [ebounty.lic] v1.1.20 infomon/effect-list compatibility

- scripts/bigshot.lic
Skip infomon.lic check if on newer Lich versions
> [bigshot.lic] v4.17.0 infomon.lic check fix for Lich 5.7.0

- scripts/ebounty.lic
This reverts commit 3c45ebd402e253e96ae8412dfd6a79c32dbea6ca, reversing changes made to 8ea07d977a969e4aa7ccf684e1ecfdbef7bd4173.
> Revert "Merge pull request #1184 from Deysh/ebounty"

- scripts/bigshot.lic
> [Bigshot.lic] added missing regex for fury

- scripts/eloot.lic
fix for assume lion to check for 25 mana if 650 already active
> [eloot.lic] v1.5.36 assume aspect fix

- scripts/puritan.lic
Rubocop cleanup and version bump for CONSTANT
> [puritan] 1.2.0 rubocop cleanup

- scripts/bigshot.lic
- scripts/overwatch.lic
hidden target monitoring.
Pushes to .targets if not present when hider is revealed.
Attempts to track when something hides.
Had an edit for bigshot UCS followup tracking, but it was a bust so removed.
> [OverWatch.lic] Initial creation.

- scripts/spellson.lic
Adding to the mix based on profanity / wizard users.
> [spellson.lic] adding GTK3 based inactivespells replacement

- scripts/ledger.lic
Add version bump and rubocop cleanup
> [ledger.lic] v1.2.0 rubocop cleanup and version control

- scripts/localchat.lic
- chore: refactor loop for simplicity and to be more rubyish
- bugfix: removed unintentional delay in closing the window with the close button
- bugfix: no longer displays non-dialog lines through better synchronization
> [localchat.lic] refactor and minor bugfixes, details in header

- scripts/boltdf.lic
Add Astral Spear 1408 and rubocop cleanup
> [boltdf.lic] v2.3.0

- scripts/localchat.lic
- bugfix: window will now allow shrinking after printing text instead of forcing a width
- bugfix: change timeout back to 0.1 from 0.01 to give get time to process before giving up
> [localchat.lic] - minor bugfix for resizing and timeouts

- scripts/bigshot.lic
Does not do this if wounded or for emergency rest
> [bigshot] v4.17.6 will perform one final loot call before resting

- type_data/migrations/5_data_consistency_fixes.rb
> [5_data_consistency_fixes.rb] #137 and extras

- scripts/ecure.lic
fix for NilClass comparison for @doneVerb
> [ecure.lic] v1.0.2

- scripts/gemsort2.lic
added additional example usage and code cleanup
> [gemsort2.lic] v1.0.3 code cleanup

- scripts/tdusk.lic
Add support for 5v5
Rubocop code cleanup
> [tdusk.lic] v1.24.0

- scripts/tdusk.lic
Anchor wave regex with start of new line
> [tdusk.lic] v1.24.1 bugfix

- scripts/resource.lic
Add messaging to use SUFFUSE ESTIMATE for 100% accuracy to chance output
> [resource.lic] v1.8.10 add SUFFUSE ESTIMATE disclaimer

- scripts/tdusk.lic
Add user selectable waggle script, more details in ;tdusk help
> [tdusk.lic] v1.25.0 user definable waggle script

- scripts/bigshot.lic
Add `ooze_escape` for getting out of Ooze, Innards inside of Hinterwilds.
> [bigshot.lic] v5.1.0 ooze_escape for HW 

- scripts/resource.lic
> [resource.lic] v1.8.11 materials update

- scripts/tdusk.lic
Fix to turn off enhancives if still considered in combat
> [tdusk.lic] v1.26.0 enhancive bugfix & experience wait

- scripts/bigshot.lic
fix missing regex match for censer command check
> [bigshot.lic] v5.1.1 censer command check bugfix

- scripts/sk.lic
Migrate to EO author and update for Ruby 3.2.
> [sk.lic] v1.1.0 initial migration and Ruby 3.2 fix

- scripts/kswole.lic
> [kswole.lic] initial migration

- scripts/resource.lic
change ranger bonus from being saved as an ARRAY to an INT
> [resource.lic] v1.8.12 ranger bonus saving bugfix

- scripts/repository.lic
update show-updatable output to list author & game for scripts
> [repository.lic] v2.47 show-updatable output update

- scripts/repository.lic
add new mapdb-check option to show last mapdb upload date, author, and if mapdb is up-to-date
> [repository.lic] v2.48 mapdb-check CLI option

- scripts/lich5-update.lic
Add depracted msging for Lich 5.7.0 usage.
> [lich5-update.lic] v1.6.0

- scripts/targetwindow.lic
Wrayth window that lists targets in the room and their status.
Supports click to target.
> [TargetWindow.lic]v1.0 Initial Release

- scripts/bigshot.lic
> [bigshot.lic] add acid to cmd_spell for 518

- scripts/targetwindow.lic
Corrected intro text.
removed unnecessary == true
> [Targetwindow.lic]v1.1 fixed some text

- scripts/log.lic
Show how to use timestamp option with autostart in header syntax examples
> chore: LOG/LOGXML expand syntax examples

- scripts/logxml.lic
> [logxml.lic] update header examples

- scripts/lich5-update.lic
Bugfix for File.open to URI.open
> [lich5-update.lic] v1.6.1

- buff_tracker.lic
Some changes submitted by Maodan.
- Converted to interactable
- Added quickload command
- Updated list output
- Prevent duplicate adding
- Updated sort algorithm
> [Buff_Tracker.lic]v.1.1 updates

- .github/workflows/rspec_tests.yml
- .github/workflows/rubocop_syntax_checker.yaml
- .github/workflows/ruby_syntax_checker.yml
- type_data/migrations/45_hinterwilds.rb
- type_data/migrations/46_atoll.rb
- type_data/migrations/50_moonsedge_crawling_shore.rb
Corrects various optional adjective descriptors for newer hunting grounds NPC types as well as for some skins.
> [gameobj-data.xml] fix for optional adjectives

- scripts/bigshot.lic
* fix to debug variable being hard set at launch to false.
* add CLI debug option to toggle debug value between true/false.
> [bigshot.lic] v5.1.9 add debug CLI command

- scripts/targetwindow.lic
Cleaned up and simplified some of my low level code.
Minimized queries to CharSettings in case it hits the database each time.
Added missing info to header and what is displayed when not using any arguments.
> [TargetWindow.lic] v1.4 clean up

- scripts/looploot.lic
> [looploot.lic] v1.2 eloot option

- scripts/tfish.lic
* Rubocop code cleanup
* Update default weights to current EG 2023 glass/glaes weights
> [tfish.lic] v1.8.4

- scripts/tfish.lic
bugfix for long description weights, curse you!!
> [tfish.lic] v1.8.5 bugfix for long description weights

- scripts/tfish.lic
bugfix caught fish detection or bo longer in fishing room
> [tfish.lic] v1.8.6

- scripts/herbhunt.lic
initial release, forked version of mandrake.lic with updates for EG 2023
> [herbhunt.lic] v1.0.0

- scripts/herbhunt.lic
add option to rest till percent experience setting, see help for info!
> [herbhunt.lic] v1.1.0 rest till experience option

- type_data/migrations/48_ebongate.rb
missing slice of ebony requiem starstone from ebongate/valuable.
> [48_ebongate.rb] add missing valuable

- scripts/linktothefast.lic
Fix nested <d> and <a> xml components
> [linktothefast.lic] v0.1.6 bugfix nested <a> & <d> components

- scripts/ecleanse.lic
> [ecleanse.lic] typos

- scripts/lich5-update.lic
Update to use release changelog notes instead of data json file
> [lich5-update.lic] v1.7.1

- scripts/bonuses.lic
Show's old-style bonuses from old infomon output
> [bonuses.lic] initial creation

- scripts/elogin.lic
Change ruby process launching from using system() to Process.spawn()
> [elogin.lic] v1.1.3 Ruby 3 process launching fix

- scripts/bigshot.lic
Added Bard routines.
Added wield command.
> [bigshot.lic] v5.2.1 additional cmds

- scripts/version.lic
Convert script into module and update output to use header version for itself.
> [version.lic] v0.59 module conversion

- scripts/symbolz.lic
[symbolz.lic] v1.1.1 rubocop cleanup
> [symbolz.lic] v1.1.1 rubocop cleanup

- scripts/ecaster.lic
Initial forking of `spellcaster.lic` to `ecaster.lic` with permission from original author. Fixes include upstream hook name fix, rubocop cleanup, slight regex additions for stances, and changing `puts` to `_respond` for terminal FEs.
> [ecaster.lic] initial release

- type_data/migrations/57_the_hive.rb
Initial creation of gameobj migration file for the new Hive area in Zul Logoth
> [gameobj] 57_the_hive.rb

- scripts/kswole.lic
Adding support for Faethyl Bog in Ta'Vaalor
> [kswole.lic] v1.0.2

- scripts/BlackArts.lic
contributers should be contributors
> [BlackArts.lic] typo

- .github/workflows/rspec_tests.yml
- scripts/eherbs.lic
send injury command to refresh XML before attempting to heal self incase missing injury from XML
> [eherbs.lic] v2.0.2 injury xml refresh

- scripts/map.lic
add RESET option to set all Settings back to default
> [map.lic] v1.1.0 reset cli option

- scripts/kswole.lic
Adding support for strandweaver in The Hive
> [kswole.lic] v1.0.3 strandweaver addition

- type_data/migrations/57_the_hive.rb
add porous chunk of rock as a breakable
> [gameobj] The Hive additional stuff

- scripts/eherbs.lic
- scripts/eloot.lic
- scripts/kswole.lic
- scripts/map.lic
republish scripts that got missed due to failing publish.yml action
> chore: republish scripts

- type_data/migrations/50_moonsedge_crawling_shore.rb
add additional gems for IMT (ME and HW areas)
> [gameobj] new ME/HW gems

- type_data/migrations/57_stormpeak.rb
initial creation of migration file for stormpeak area
> [gameobj] Stormpeak

- scripts/kswole.lic
Fix Rift/Scatter lich spell preps
> [kswole.lic] v1.0.4 RiftScatter lich fix

- scripts/eherbs.lic
bugfix for Zul Logoth location check
> [eherbs.lic] v2.0.4 Zul Logoth fix

- scripts/mybounty.lic
moving to EO from Luxelle per permission
> [mybounty.lic] migration to EO author

- scripts/ecure.lic
correct sleep/pauses for CURE usage for less than 3 second RT
> [ecure.lic] v1.0.3 CURE rt correction

- scripts/effect-list.xml
Update effect-list.xml with various updates from the Spell Disabler Review https://discord.com/channels/226045346399256576/1191064189981163611
> chore: spell disabler update

- scripts/version.lic
upstream/downstream hook sources support with Lich 5.8.0
> [version.lic] v0.60

- scripts/effect-list.xml
Change 535 Haste to be multicastable.
> [effect-list.xml] 535 multicastable

- scripts/foreach.lic
Rubocop cleanup & Fix for constant variables
> [foreach.lic] v1.0.5 constant variable fix

- scripts/foreach.lic
Remove experimental feature, no longer used
> [foreach.lic] v1.0.6 remove experimental feature

- scripts/kswole.lic
Add Bonespear messaging for eidolons
> [kswole.lic] v1.0.5 Bonespear initial support

- scripts/lnet.lic
Remove combat leadership skill
> [lnet.lic] v1.9 remove combat leadership skill

- scripts/0net.lic
Remove combat leadership skill
> [0net.lic] v0.0.6 remove combat leadership skill

- scripts/overwatch.lic
- added additional hafling cannibal messaging
- added Flaming Aura 1706 reveal messaging
> [overwatch.lic] v1.2.1 additional messaging

- scripts/ebounty.lic
remove forced HIDE for foraging put in by error.
> [ebounty.lic] v1.1.36 HIDE bugfix

- type_data/migrations/59_additional_reagents.rb
add additional reagents that are missing and that were recently added
> [gameobj] additional reagents

- scripts/ebounty.lic
add option to HIDE back for no-magic rooms if enabled to hide.
> [ebounty.lic] v1.1.37 additional HIDE/no-magic fix

- scripts/eherbs.lic
fix for wrong variable reference
> [eherbs.lic] v2.0.5 fix for wrong variable reference

- scripts/kswole.lic
Support for additional IMT prep phrases
> [kswole.lic] v1.0.6 additional IMT messaging

- scripts/eloot.lic
fix for bulk selling skins when bundles are worth to much to sell via bulk sell
> [eloot.lic] v1.6.18 bulk sell furrier fix

- scripts/BlackArts.lic
fix for check_table including itself in contents returned.
> [BlackArts.lic] v1.1.2 check_table fix

- scripts/echild.lic
add CLI option to disable disablers via ;echild nodisablers
> [echild.lic] v1.19.0 add option to disable disablers

- scripts/bigshot.lic
fix for cmd_briar to use MEASURE instead of LOOK due to gamefeed issue with extended show descriptions
> [bigshot.lic] v5.3.3 bugfix for cmd_briar

- scripts/bigshot.lic
fix to add Tangle Weed (610) status of "entangled" to the PRONE regex
> [bigshot.lic] v5.3.4 various Tangle Weed (610) fixes

- scripts/version.lic
add account and game type to output
> [version.lic] add game/account type

- type_data/migrations/60_cursed.rb
add rift cursed herbs to `cursed` gameobj type
> [gameobj] add additional cursed herbs

- scripts/eloot.lic
additional open/close messaging
reduce timeout on Lich::Util.quiet_command_xml from 5 to 2 seconds
> [eloot.lic] v1.6.23 couple fixes

- scripts/eloot.lic
update change_stance to use percentstance and CMAN STANCE
> [eloot.lic] v1.6.24 CMAN STANCE support

- scripts/effect-watcher.lic
Adds initial PR for Tysong to cleanup :imp:
> feat(effect-watcher.lic): add initial pr;

- scripts/effect-list.xml
- scripts/spell-list.xml
apparently people are using it. weird.
> [effect-list.xml] i guess mindwipe exists

- scripts/banditpatrol.lic
- scripts/shift.lic
Migrating `banditpatrol.lic` and `shift.lic` from Brute/Ryjex as he no longer wishes to maintain nor troubleshoot script and wants to offer them to the community for further support. Rubocop cleaned up both scripts and updated some of the code to use newer Lich5 API calls.
> [scripts] banditpatrol & shift takeover

- scripts/ebounty.lic
add exit if gembounty is determined complete but using eloot sell with exclusion to not sell gems
> [ebounty.lic] v1.3.5 gem bounty loop when no selling

- scripts/repository.lic
* convert global vars to Lich5 constants
* add default save location for yaml/json to DATA_DIR
* remove code for upload-lich5/download-lich5 commands
> [repository.lic] v.2.53 code cleanup

- bin/repo
> [bin/repo] Update to manage without SSL Cert

- scripts/ebounty.lic
add timer to not spam INFO during should_hunt? method
> [ebounty.lic] v1.3.8 fix INFO spamming

- scripts/enhancives.lic
Ever get tired of losing crumbly enhancives because the SImu generated warning message got lost in combat or some other massive screen scroll?
Ever wanted to know over time how often your enhancives lose their charges?
Pre-production test run of the solution!
> [new][gs][enhancives.lic] Tracks enhancives

- scripts/enhancives.lic
Time to take charge of enhancive charges and such!
> [gs4][enhancives.lic] Add tracking and charge history for enhancives

- scripts/bigshot.lic
fix for ROOM command check to work properly
> [bigshot.lic] v5.3.16 ROOM bugfix

- scripts/eherbs.lic
bugfix for excessive ANALYZE for determining survival kit logic bugfix for wait_rt method
> [eherbs.lic] v2.0.13 bugfix ANAYLZE spam

- scripts/ecleanse.lic
Update to include WoT unpoisoning
> [ecleanse.lic] v1.1.1 Wall of Thorns unpoison

- scripts/eherbs.lic
fix for survival kit to persist thru current session running so that does not have to reanalyze the kit on every usage
> [eherbs.lic] v2.0.17 bugfixs for ANALYZE not being available

- scripts/bigshot.lic
* update $bigshot_status to utilize :ready instead of :hunting when clear to hunt
* update $bigshot_status to :hunting when arrived in do_hunt() and actually starts hunting
> [bigshot.lic] v5.7.8 $bigshot_status value change
