scripts/absorb.lic

Experience pulse utility script
By default, this script will run in the background and announce experience gains as they are absorbed.
Also supports some actions around pulses and mind saturation:
* Run until experience absorbed and then exit (ala ;pulse.lic)
* Run a command or start another script on an experience pulse (ala ;errand.lic)
* Log off when mind clears or reaches a specified level

Add ;absorb utility for experience pulses

---

scripts/notify.lic

Some minor changes to ;notify that I have been meaning to submit for a bit for discussion. These three commits should all be independent from each other so we can take out/change anything you don't like.
The Regexp.union change has almost the exact same behavior as your existing monkey patch, but I try to minimize the use of those if there is a built in way of doing it. The Regexp method also preserves flags like `/ignore case/i` when combining regexs.
I updated the help to include the play command but also made the script try to play a sound when changing it as this is the behavior I expected.

;notify tweaks

---

scripts/notify.lic

1. Updates notify to create a background TCP server that accepts messages from all clients and forwards them to the system notification library
2. Uses a hybrid TTL/LRU cache mechanism to rate limit messages from clients

use a tcp message sink;

---

scripts/wps.lic

This script will request multiple services from the smithy. It tries to be strict about what it will accept for input and to verify that a blacksmith NPC is present before requesting services.
This is kind of overkill for a script that provides minimal utility over `;e count.times { ... }`, but I wanted to ride out the command pattern and some simple extract method refactoring to see where it landed. Welcome any feedback if you have any as I have a couple points for discussion.

;wps: Smithy helper script v1.0

---

.travis.yml

I was paranoid about accidentally publishing in #17, so I created this PR to just to move `util/repo` from the script step to the deploy step.

Move lich repo publishing to deploy step in CI

---

lib/lich/gameobj.rb
lib/spec/factories.rb
spec/gameobj-data/aggressive_npc_spec.rb
spec/gameobj-data/core_spec.rb
spec/gameobj-data/passive_npc_spec.rb

This adds specs for the NPC types in the GameObj XML data file. I added Lich's GameObj implementation in `lib/lich/gameobj.rb` since it doesn't seem feasible to require the full lich.rb.
I set these specs up with one assertion per example and there are roughly 3000 examples here, but the suite still completes in ~2 seconds in Travis.
While creating these specs, I found a few issues with the existing data and have left these as pending examples to fix in the future in a separate PR.

gameobj-data.xml specs for NPC categories

---

lib/spec/factories.rb
spec/gameobj-data/alchemy_spec.rb
spec/gameobj-data/gem_spec.rb

Adds specs for gem-like things (gems, valuable, scarabs, plinite) and alchemy (reagent, products, and equipment) for the gameobj-data.xml file.

gameobj-data: gem and alchemy data specs

---

scripts/wps.lic

Removes a couple of extra quotation marks from the confirmation message and automatically registers the item after performing services.

wps: fix confirm msg and register items after service

---

scripts/puritan.lic

Fixes a bug where the script would hang if you attempted to use puritan with some set of other spellsongs active. When this occurs, the string reads "You weave another verse into your harmony, directing the sound of your voice at ..." The script, however, only returns "ok" upon encountering "You sing a melody, directing the sound of your voice at ..."
My fix simple checks for the presence of the shared portion of those two strings. Alternatively, you could solve this with comparing two different strings using starts_with; I felt this was more elegant. YMMV!

String check fix for puritan cast attempts

---

.travis.yml

Bundle 2.0 was released today and requires rubygems to be at least version 3.0. This tells our build to update `gem` before trying to install bundler and the rest of our dependencies.

travis: update rubygems version to support new bundler

---

scripts/puritan.lic

When using 1004 on a gem, the gem damage messaging (i.e. improvement or strain) comes before the messaging for a gem purified to orb status. This updates the script to continue processing the 1004 result after the gem damage messaging until sees the orb messaging, the generic non-orb messaging from 1004, or another result that cannot result in an orb gem.

Orb outcome from 1004 overrides other outcomes

---

.travis.yml
bin/migrate

This uses the `xmllint` cmd from the libxml` library to verify that the compiled output is valid XML and to autoformat it using xmllint's default rules. libxml2/xmllint are available out of the box on OSX and many linux distros (and easy to install on distros where it doesn't come by default, but it doesn't look like there is an easy way to make it work on Windows. The best directions I found were from [Atom's xmllint package](https://atom.io/packages/linter-xmllint) but they are pretty complicated and use a somewhat out of date version of xmllint.
@horibu if you get a chance, could you try to run `bin/migrate` on Windows without installing anything? You should get an error message about formatting the XML file but everything else should work right.
@ondreian do you think this is the best …

gameobj-data: use xmllint to verify and autoformat compiled output

---

lib/migration/change-set.rb
lib/migration/migrator.rb
lib/migration/table.rb
type_data/migrations/5_data_consistency_fixes.rb
type_data/tables/armor.yaml

Adds a `create_key` command to the migration DSL. Refactors one of the existing migrations to exercise the new command.

Adds create_key command for migrations

---

scripts/cluster.lic

Lich's `wait_while` / `wait_until` are too slow imho for the busy wait that checks for a response to a request. This replaces the `wait_while` block in `Cluster.request` with a loop on a 1ms sleep. I tested this out and didn't notice an increase in CPU usage, but I am going to try some other things too. I think I can have `_handle_response` invoke a block or resume execution of a fiber instead of polling.

cluster: faster response processing

---

scripts/webui.lic

Basic proof of concept of web app for presenting a configuration UI and info display from lich scripts. The server spawns in a separate thread and renders a server-rendered UI for editing Lich variables and WebUI server settings. I started to separate some concerns to create the beginnings of a framework that other scripts could use as well, but wanted to get some feedback before I committed to any direction.
Here are some screenshots:
An explicit goal of this script was to only use gems available in the Ruby standard library. I generally avoid [WEBrick](https://ruby-doc.org/stdlib-2.0.0/libdoc/webrick/rdoc/WEBrick.html) in production because it is single-threaded, but I felt like it worked well enough for this purpose. I implemented a server-side UI built around HTML forms using …

WebUI: A web interface for Lich scripts

---

lib/migration/table.rb
spec/gameobj-data/boxes_and_picking_spec.rb
type_data/migrations/13_use_names_not_nouns_for_loot_boxes.rb

Updates the `box` type to use exact names instead of just relying on the noun. This lets up drop the existing excludes we had as well. `;xmlpatch` has been doing this with a very similar regex for a while and I feel pretty confident that my list of box combinations in the specs is exhaustive, so I think this is safe to deploy to everyone.
This also updates the migration code to not write XML tags for empty rulesets. It was putting a couple tags like `<noun>^()$</noun>` in the XML which would never match but are kind of confusing.

gameobj: use names instead of nouns for treasure boxes

---

spec/gameobj-data/skin_spec.rb
type_data/migrations/18_celebralite_tentacles_have_barbs.rb

Should be "barbed cerebralite tentacle" as single skin. Bundles are "bundle of cerebralite tentacles" so I am keeping the shorter description in there too. War griffin talons are "bundle of griffin talons" when bundled.

gameobj: single celebralite tentacle and war griffin talon bundle fixes

---

scripts/wps.lic

According to Estild, wps changes are automatically registered, and this is a double registration.

fix(wps.lic): remove registration call

---

spec/gameobj-data/gem_spec.rb
spec/gameobj-data/junk_spec.rb
type_data/migrations/21_gh_133_teras_creature_drops.rb

Also adds the occasional "hollow smooth black glaes" drop as junk since its heavy and wasn't sellable anywhere for me. Also excludes both of these from uncommon. 
Fixes #133

Adds skayl hearts as sellable gems

---

scripts/tears.lic

Was about to upload a quick script I hacked together to do tear calculation, figured it just made more sense to pull in changes here and keep it all together.
```
>;tears calc 25 30
-------------------------------------------------------------------------------------------
| Current      | New          | Cost (ess)   | Cost (wks)   | Total (ess)  | Total (wks)  | 
-------------------------------------------------------------------------------------------
| 25           | 26           | 4800         | 0.3          | 4800         | 0.3          | 
| 26           | 27           | 7200         | 0.45         | 12000        | 0.75         | 
| 27           | 28           | 9600         | 0.6          | 21600        | 1.35         | 
| 28           | 29           | 12000        | 0.75         | …
```

feat: adds calc option for tears.lic

---

scripts/bigshot.lic

added flying and !flying as command checks for bigshot. Useful to issue commands to knock something out of the air or to not attack if the creature is still in the air.

add flying check

---

scripts/bodega.lic
scripts/tilde.lic

Adds the ability for `:` to be used to integrate `vars.lic` settings with `tilde.lic`, which means you can trivially create cross character macros without caring about each character's underlying settings.
example:
```xml
<key id='alt'>
<key id='p' macro='\x~:lootsack \?' comment='put :thing in my :lootsack'/>
<key id='t' macro='\x^:lootsack \?' comment='take :thing from my :lootsack'/>
<key id='l' macro='\x~:lootsack\r' comment='look in my :lootsack'/>
<key id='n' macro='\x~:harness \?'/>
<key id='u' macro='\x^:harness \?'/>
</key>
```

feat(tilde.lic): add ability to integrate with ;vars

---

scripts/treim.lic

Logic is pretty simple:
• If you have sufficient mana and there's no rare, use 435
• If you have insufficient mana and there's no rare, use open mstrike
• If there's a rare, use focused mstrike - then, if you have sufficient mana, use 435 - otherwise, use open mstrike

Adding "scrub" option to support mstrike + 435

---

scripts/tgames.lic

Changing the rummage_bucket=false routine to redeem seashells instead of stowing

Update to redeem seashells when found

---

scripts/treim.lic

Treim 1030 has the unfortunate side effect of issuing several commands. This prevents getting hits in on many fast-dying waves. As such, I've modified the routine to send a single command that handles the casting: `incant 1030 open`
Based on verified bardic research, this command uses the RENEW 1030 cost where appropriate and is open-targeted as desired.

Improved treim 1030 performance

---

scripts/reimmessage.lic

There are *two* places where officers are specified; I only changed one

Another fix

---

scripts/bigshot.lic

Adds a check for "obvious hiding" players and sets the variable that tracks if an ambusher is in the room.

Added check for "obvious hiding" players (SET ObviousHiding ON)

---

scripts/bigshot.lic

`$ambusher_here` is reset during `variables_reset`, which is called after a character walks into a new room, which is also after the server_string has already been processed (so the subsequent variables_reset then clears `$ambusher_here` immediately after the flag is set).
This switches to using a separate variable and resets it in a different spot to work around this issue.

bigshot: track obvious hiding msg separately from ambusher_here

---

scripts/bigshot.lic

adds inside / outside command checks
useful for baby rangers and, to a lesser extent, anyone who uses 125 for anything other than opening boxes.

bigshot: add outside/!outside checks for attack commands

---

scripts/treim.lic

I had this changed to cast 118 instead of 1115 locally for a while but switched back to master and poofed all the rares on our nightly Reim run. I thought about changing it for everyone but a lot of people have trouble warding rares with 100s and the poofing isn't an issue if you don't have manipulation lore.

treim: adds empoof routine to avoid poofing rares

---

type_data/migrations/28_necrotic_ring_ghostly.rb

Initial start of fixing ghostly mobs to be detectable that were introduced from the EG 2019 necrotic ring.

EG Necrotic Ring - ghostly mobs fix

---

scripts/briefcombat.lic

0.0.7 (2020-05-14)
Added parameter options:
-x        Extreme mode, will squelch searches and spell messaging.
[player]  Added ability to not shorten actions by specific players
Removed spell number to improve immersion
Now retains a little bit of spell cast color, for immersion
- This can be disabled with the "-x" parameter
Improve handling of bard song weaving
Fixed a known issue, now (more) accurately counts kills and status effects
Added indentation to kill / stunned counts

briefcombat v0.0.7

---

scripts/cartograph.lic

1. add support for the Git based mapdb in [elanthia-online/cartograph](https://github.com/elanthia-online/cartograph)
2. add support for Travis built `.hmr` (Marshal format) for MapDB quick-loads

feat(cartograph.lic): add support for Github based MapDB

---

scripts/0net.lic

[source](https://ruby-doc.org/core-2.6.3/Marshal.html#load)
> By design, ::load can deserialize almost any class loaded into the Ruby process. In many cases this can lead to remote code execution if the Marshal data is loaded from an untrusted source.
There is almost no source more untrusted than an lnet message, so we should **never** use Marshal data here.
This is unfortunately a break change as it makes `send_data` a `noop` for now, but it must be done for safety concerns.  I have reported this vulnerability to Tillmen and he has implemented some mitigations on the lnet server for regular `lnet.lic` users, but any use of `Marshal` in this manner is inherently insecure.

fix(0net.lic): RCE exploit when on lnet

---

scripts/bigshot.lic

name: Falicor
about: Feature discussion
Added ability for followers to use the newly added LTE boost feature and to fix issues with group hunting caused by the overkill feature.  I also modified fried hunting to be more "user friendly" and changed tool tip on the fried hunting commands to clearly spell out the choices.
Was trying to group hunt with my characters and could not get the features to work as expected.  It ended up being a combination of user error, documentation issues and script defects/omissions.  
Previously, if you had overkill (or, later, LTE) >0 on a follower, the hunt would only end once OOM/Encumbered/Injured.  If nothing was filled in the 'fried hunting commands' box, the character would stand there and do nothing instead of defaulting to hunting actions.  There are …

 Request For Comment (Bigshot)

---

scripts/wps.lic

Updated to work for sighting. Was expecting the wrong response from the blacksmith. Tested with crit, damage, and sighting with these changes.

wps: fix sighting support

---

scripts/tears.lic

They added commas to `info` and this is one of the things that broke.

tears: update info regex to work with commas in numbers

---

README.md

I don't think anything else needs to be update inside the repo but let me know if you think of something else.

Migrate build status badge in README to travis-ci.com

---

scripts/treim.lic

It gets dumb if a clear check is requested while there is still an unlooted dead rare in the room. This updates it to only pause responding to the clear check if the rare is still alive.

treim: only block responses to clear checks if the rare if still alive

---

scripts/isquelch.lic

This fixes two issues found by users that were caused be recent refactoring. The first is that a `string.length == 0` was changed to `.zero?` when it should have been `.empty?`, and the second was a variable renaming missing one instance.

fix: use empty? instead of zero? on a string, and fix an invalid variable name.

---

scripts/isquelch.lic

Adds a command to import squelches from a StormFront settings XML file. Also improves the command interface so the first command is parsed, to eliminate a separate starting command. Also adds examples and improves the help statements slightly.

Add StormFront importing to isquelch, and accept first command

---

scripts/isquelch.lic

Add a command to export squelches to isquelch, so squelches can be shared between individuals. This includes both bulk export, or specified by index.

Add export command to isquelch

---

scripts/tears.lic

- updates calculations to use new essence scheme
- dedupes some inline code to functions for the silver/dollar rate calculation table
- adds "old rate" column for the calc table so people can easily reference costs for the old numbers
example outputs:
range with no rate specified
```
>;tears calc 20 25
--- Lich: tears active.
Calculating essence needed to take an item from 20 to 25
-------------------------------------------------------------------------------------------
| Current      | New          | Cost (ess)   | Cost (wks)   | Total (ess)  | Total (wks)  |
-------------------------------------------------------------------------------------------
| 20           | 21           | 6250         | 0.13         | 6250         | 0.13         |
| 21           | 22           | 6562         | …
```

tears.lic: update for new essence numbers

---

scripts/puritan.lic

After a recent update, ;puritan stopped saving most orb gems for me. I figured out it was checking naturally orbbed gems but was treating sung gems the same regardless of whether they were orbs or not. This updates puritan to respect the orb bag setting and also to loresing to orb gems if the loresing option is enabled to check for mage rechargeable gems.

puritan: loresing to orb gems if option is enabled

---

scripts/jinx.lic

...with grouped subcommands. Also, --repo seems to be applicable to all
script actions, not just install and list, so I made the doc say that.

Make it more clear that jinx splits into two "commands"

---

scripts/treim.lic

Extends the Cease fire command to recognize any OOC whisper from the leader that includes the phrase "KILL THY SCRIPTS". Also updates this command to break out of the loop if we leave Reim or move into the Throne Room.

treim: Autochill when leader says KILL THY SCIRPTS

---

.gitignore
scripts/bigshot.lic

I got tired of having the Dreavening line "There is nothing to report at this time, chief." cause an interaction window to pop up.  When I went to add something to the interaction monitor to ignore that, I realized that both the expressions to watch for and the expressions to ignore should be configurable, so I wrote this.
I've moved the options for the interaction monitor to their own settings tab named "Monitoring", and created text areas there for easy editing of multiple expressions.  The joined expressions are split for the text areas but stored as single string.
I also did some drying up of the code that creates the settings window to make adding a window easier, and to make the code a little more compliant with the general Ruby community style.

 Add interaction monitor options to specify expressions

---

.github/workflows/build.yml

Sets up a workflow to run tests and push releases to Tillmen's repo. Right now both this and Travis will run but I plan on disabling Travis soon if the GH version seems like its working.

chore: set up GitHub action to run build and tests

---

.github/workflows/smoke_test.yml
Gemfile
spec/jinx/jinx_spec.rb
spec/jinx/repos/archive/assets/noop.lic
spec/jinx/repos/archive/headers/noop.header
spec/jinx/repos/archive/manifest.json
spec/jinx/repos/core/assets/alias.lic
spec/jinx/repos/core/assets/autostart.lic
spec/jinx/repos/core/assets/demo.lic
spec/jinx/repos/core/assets/go2.lic
spec/jinx/repos/core/assets/infomon.lic
spec/jinx/repos/core/assets/lnet.lic
spec/jinx/repos/core/assets/spell-list.xml
spec/jinx/repos/core/assets/vars.lic
spec/jinx/repos/core/headers/alias.header
spec/jinx/repos/core/headers/autostart.header
spec/jinx/repos/core/headers/demo.header
spec/jinx/repos/core/headers/go2.header
spec/jinx/repos/core/headers/infomon.header
spec/jinx/repos/core/headers/lnet.header
spec/jinx/repos/core/headers/vars.header
spec/jinx/repos/core/manifest.json
spec/jinx/repos/extras/assets/noop.lic
spec/jinx/repos/extras/headers/noop.header
spec/jinx/repos/extras/manifest.json

Sets up Webmock to respond to repo URIs to serve the manifest and assets locally. 
* By default, the specs will use the local repo servers. We accomplish this by mapping local directories to each repo domain used in the tests. This is really fast:
```
> rspec spec/jinx/jinx_spec.rb
..............
Finished in 0.189 seconds (files took 0.27725 seconds to load)
14 examples, 0 failures
```
* You can also set the `ENABLE_EXTERNAL_NETWORKING` environmental variable run the specs against the live external servers. This takes a bit longer:
```
> ENABLE_EXTERNAL_NETWORKING=true rspec spec/jinx/jinx_spec.rb
..............
Finished in 13.2 seconds (files took 0.27649 seconds to load)
14 examples, 0 failures
```
* I also created a Github Actions workflow to run the jinx spec against the live servers …

jinx: enable specs to run with and without mocked external API

---

.github/workflows/build.yml

Runs the tests against all ruby versions supported by GitHub's setup-ruby actions: 2.4, 2.5, 2.6, and 2.7. These are all of the [currently maintained Ruby versions](https://www.ruby-lang.org/en/downloads/branches/) except 3.0 which was just released and has some pretty big probably lich breaking changes.

Run build against ruby matrix

---

.github/workflows/publish.yml
.github/workflows/test.yml

This avoids us releasing 4 times (one for each ruby version in the matrix). There is a fair amount of repetition in the workflows but I don't know Actions well enough to DRY it up yet.

build: split test and release actions

---

scripts/jinx.lic
spec/jinx/jinx_spec.rb

I broke this and it was putting everything in `$data_dir/` instead of $data_dir/_jinx`

jinx: fix for Jinx::Folder.path to use the correct base dir

---

scripts/jinx.lic
spec/jinx/jinx_spec.rb

* Tracks metadata (installed digest and source repo) when script or data file is downloaded in scripts.yml and data.yml respectively.
* Uses the digest stored from the last download time to prevent locally modified files from being overwritten by updates. Will abort the download if the digest of the local file doesn't match that of the last downloaded version.
* Adds a new --force option to install/update to overwrite existing files even if they have been modified.

jinx: track metadata for installed scripts and data

---

scripts/oleani-lib.lic
scripts/poolparty.lic

I added a new option flag to toggle looking in each box prior to looting it (--look-in-box), which is set to false by default to maintain the current behavior.  
Fixes #355 
Additionally, added a new error and handling code for attempting to deposit a box which is already unlocked.  If this happens, the box is placed back in the loot sack and additional information is printed at the end of the deposit step.  If no such failures occur the print out at the end of the step is the same as before.

New option to look in boxes before looting and error handling for already unlocked boxes

---

scripts/tdusk.lic

Added a new variable, defaulted to true, for casting 418 as a sorc/wizard.
This shouldn't break anything for existing scripts, but will let folks - moving forward - disable it when running with a bard, for example.

Support for a Node variable for 418

---

.github/workflows/test.yml

The upstream action deprecated this ruby version because its very old.
```
Run actions/setup-ruby@v1
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 2.4 not found

Remove Ruby 2.4 from test matrix 

---

scripts/resource.lic

The error message for when the starting bonus was less than the ending bonus returned an error to the user stating to use ';tears calc [start] [end]'. This fixes the error so it says ';resource calc....', which is the correct reference since ;tears was deprecated.

Remove ;tears reference

---

scripts/jinx.lic
spec/jinx/jinx_spec.rb

Adds post-install hooks for spell-list.xml, gameobj-data.xml, and mapdb.json. They all reload the newly downloaded data file, and the mapdb hook also attempts to download any image files referenced in the mapdb that aren't already present in the map directory.

jinx: post-install hooks and mapdb.json

---

scripts/resource.lic

```
;resource bonus
Sanctify Success Formula
---------------------------
68 : Level
+  26 : WIS Bonus
+   4 : INF Bonus
+   3 : trunc(MIU ranks/10)
+   3 : trunc(AS ranks/10)
+  34 : trunc(SMC ranks/2)
+ 164 : Cleric Spells
+  20 : Shrine Bonus (10 if aligned to pantheon but not your specific deity)
===========================
Total of 322
--- Lich: resource has exited.
>;resource chart
--- Lich: resource active.
Resource needed per tier profession services
T1 Sanctify -  50,000 Devotion
T2 Sanctify -  75,000 Devotion
T3 Sanctify - 100,000 Devotion
T4 Sanctify - 125,000 Devotion
T5 Sanctify - 150,000 Devotion
Add Perm Holy Water Flares to T5 Sanctify - 200,000 Devotion
--- Lich: resource has exited.
```
Add proposed cleric values from 330 doc to chart/bonus. With checking from a cleric, …

resource.lic: add proposed cleric for 330 values

---

type_data/migrations/9_skin_fixes.rb

these show up as:
noun => talon, name => eagle talon
when held in hand, but when in a container/laying on ground as:
noun => talon, name => moor eagle talon
so need to add explicitly to be caught by sloot et. all

gameobj-data: add moor eagle talons to skin and furrier

---

scripts/resource.lic

Zelnorn (-999) and Adamantine (-500) had the wrong difficulties listed in the materials table. I updated them to the correct values, -250 and -150, respectively.

Fix Zelnorn and Adamantine

---

scripts/lich5-update.lic

To support the recently reverted 5.0.18 lich.rbw build, the updater process now has a '--revert' argument feature, which will scan for the last lich file saved during a lich5 update process (legacy or current script files).

add feature --revert to lich5-update

---

scripts/lich5-update.lic

The --snapshot feature fails in certain test cases where the existing lich version is the same as the current json lich version.  These changes address validations and permit the --snapshot feature to function.  Adding directly to master branch to limit poor update experiences.
Third time's a charm?

Update --snapshot lich5-update

---

scripts/lich5-update.lic

Per Rinualdo - reduce confusion by returning a message when the script is run but no action is needed, or when the script is run without parameters / arguments.

Update text / reduce confusion - lich5-update

---

scripts/invoker.lic

Removing the `self.` def that causes method `initialize` to be private.  Making it public seems to allow the script to run but requires testing.

Defect - change initialize method to public

---

scripts/oleani-lib.lic

A change to inventory full this morning broke the starting capture. The change to the regex fixes it (There may be a more regex-ish way to fix it but this has been tested to work).

Update Oleani-Lib for INVENTORY FULL Change

---

scripts/briefcombat.lic

Fixed 917 so it's identified properly instead of being lumped with 635

briefcombat v0.0.8

---

scripts/infomon.lic

Infomon change to add ' - Cooldown' to Spell name to differentiate between Spell effect and Cooldown effect while spell-list.xml remains in play.
Resolves #567

Fix - infomon deduplicate spell from cooldown

---

scripts/bigshot.lic

Updates to BS bring rev to 4.7.4
Ignore animates as NPCs
Do not stand if looting (or loot script) is active
Update bless methods to stop if checked, hunt if not but register a bless would benefit
Concepts - Rinualdo

Update bigshot animates, blessing and standing while loot script running

---

scripts/bigshot.lic

in crowded hunting areas, previous bless needed detect logic would not discern between Char.name and other hunters.  Most false positives addressed, but there may still be occasional observations.

Update bless logic to reduce false positives

---

scripts/spell-list.xml

the dothistimeout in the cast proc is wrong.
old: "As you concentrate on **the signal**"
correct: "As you concentrate on **your sigil**"

[spell-list] fix typo for cast-proc of sigil of power

---

scripts/bigshot.lic
scripts/shoard.lic

Adds support for standard (not-Premium) lockers
Adds HELP. See ;shoard help
Locker add/delete: Changed logic to use current room if no room specified
Locker add/delete: Removed "locker" mapdb tag check due to unreliable/incomplete tagging
Entry fixed for locker entry rooms that don't expose the "opening" or "curtain" in the loot or room description

fixes to standard lockers, entry, added help

---

scripts/autostart.lic

Adding a check for DR, and putting in play a method to automatically download / run the DR script dependency if it hasn't been recorded as run and if two key files cannot be found.
Needs DR specific testing on both existing installs and brand new installs.
(Remade due to workflows not able to update in a PR after started, see #626 for original)

Adding a check for DR / dependency runs

---

scripts/bigshot.lic

cman stance perfection - use 10,20,30,ect in attack stance box to use stance perfection if you know it.
assume aspect - use '650 lion wolf' '650 lion evoke' in society box or 'assume lion wolf' 'assume lion evoke' in hunting commands.
briar weapons - 'briar \<weapon\>' 'briar bow' 'briarbow' in hunting commands to activate +AS buff.
dhurl fix - added weapon bond return message to monitor so dhurl/recover can see if a weapon auto returns from bonding and doesn't end up in a recover loop. Warriors rejoice.

stance perfection, assume aspect, briar weapons support and dhurl fix.

---

scripts/eherbs.lic

User reported defect - `an earthworm potion`
Logic corrected to strike `an` in the menu to match and order the potion.

[eherbs.lic] Small correction to remove 'an' where appropriate

---

scripts/jinx.lic
spec/jinx/jinx_spec.rb

Prevent downloading of data as a script to script folder and vice versa.

[jinx.lic] prevent download as opposite type

---

scripts/bigshot.lic

Issue with cmd_spell failing due to hard RT as no waitrt? in the command.

[bigshot.lic] cmd_spell waitrt? missing

---

scripts/resource.lic

adds explicit numbers for grit for hybrid weapon types by defining the hybrid (katar, bastard sword / katana) and the associated weapon types that make up it's skill (have to make sure to skip the "hybrid" skill as a secondary number for all weapons, and define ignore the hybrid's own sub-skills so they don't get counted twice. hence the more complex reject logic)

[resource.lic] add explicit grit numbers for hybrid weapons

---

scripts/eforgery.lic

Moved `oil_trough`, `material_oil`, and `oil_order` to be inside the `forger` class as only used inside of it and was causing not found issues.

[eforgery.lic] variables not defined in class

---

scripts/go2.lic

Fix for using go2 with getsilvers enabled and not having enough at bank. Will exit with an echo statement stating such. Addresses #673

[go2.lic] v1.35 exit if not enough silvers

---

spec/gameobj-data/gem_spec.rb
type_data/migrations/7_sos.rb

Some of these were recognized as gems but didn't have sellable values.
- age-darkened ivory crescent
- blackish blue idocrase
- cloudy alexandrite shard
- faceted blood red sandruby
- fossilized bessho lizard spur
- formation of rainbowed bismuth
- piece of striated fluorite
- radiant green cinderstone
- square of shale rock
- swirled lightning glass shard
- variegated violet tanzanite
Also `twisted iron spiral` wasn't recognize as a gem at all, so I updated the migration to include that as well.

[gameobj] ensure that all of the Sanctum gems are also gemshop sellable

---

scripts/eloot.lic

Remove change from self.valid_objs(objs) and corrected proper spot in self.reject_invalid_loot(objs) call.

[eloot.lic] uncommon disk proper fix

---

scripts/xnarost.lic

Somewhere we lost the @theme_state rewrite shifting from 'on | off' to 'true | false'.  This change corrects @theme_state to be 'true | false' as it is presently stored / used in lich5.

[xnarost.lic] Update @theme_state

---

scripts/bigshot.lic

Since it is considered slamming to log out in an attempt to prevent your death. Would hate for someone to get banned from something they are unaware of.

[bigshot.lic] Update dead man's switch to only work in GSF

---

scripts/ebestiary.lic

- on initial run pulls down the Creatures By Level page from the wiki in order to build a list of creatures and their level
- this then happens only once manually invoked, or once every 30 days to ensure new creatures are brought in
- can then list creatures by a level range, filtering by a search term that mathces on creature TYPE (as defined by gameobj-data) or name
- creatures with no valid type will display as UNKNOWN and always come back in a search (likely needs fix in gameobj-data)
- default is to level by +/- 5 of your current level if no level arguments passed

[ebestiary] adds ebestiary

---

scripts/bigshot.lic

fixed briar <weapon> to work when briar weapon in off hand of twc.
bigshot quick will not skip spells when out of mana instead of standing aroud waiting.

[bigshot.lic] added tailwind command check

---

scripts/bigshot.lic

Changed 1040 to have a checkbox. When enabled will check self and group members for status ailments, and shout 1040 to attempt to clear them. 5 second timeout to keep from multiple casts back to back. This may need to be adjusted. 1040 seems to be RNG without heavy lores. Will need to find the balance between effective and blowing all your mana, or maybe this is just left up to the user.
Pull players to feet will no longer pull kneeling players.

[bigshot.lic] fixed shield bash for semi's

---

scripts/bigshot.lic

Changed 1040 to have a checkbox. When enabled will check self and group members for status ailments, and shout 1040 to attempt to clear them. 5 second timeout to keep from multiple casts back to back. This may need to be adjusted. 1040 seems to be RNG without heavy lores. Will need to find the balance between effective and blowing all your mana, or maybe this is just left up to the user.
Pull players to feet will no longer pull kneeling players.
Don't fix white space issues in the middle of the night right before bed.

[bigshot.lic] fixed shield bash for semi's (typo free this time)

---

scripts/bigshot.lic

gave frozen its own command check because PRONE spectral protectors can still reflect arrows while frozen ones cannot. So need it to be more accurate for frozen. It's still part of prone check.
dislodge <location> - would only attempt to dislodge if an arrow sticks in this location (dislodge eye head neck chest back abdomen arm hand leg)
It piggy backs on existing archery tracking. Will record target id and location of latest arrow that lodges. Then dislodge will fire if your current target id matches the lodged target id and location matches one you want to dislodge from. This works great as a lone archer. Could pose a problem with a group of archers as first person/third person messaging is the same. So someone smarter may want to look into it. But for now, this greatly expands the …

[bigshot.lic] expanded dislodge command

---

scripts/bigshot.lic

society box.
Added command check for kneeling (k) (!k)
Will no longer stand if you are hidden. This posed an issue for crossbow users being unable to kneel, hide, and fire.

[bigshot.lic] added burst of swiftness 9625 in

---

scripts/bigshot.lic

Bugfix for 9625/burst of swiftness

[bigshot.lic] 4.12.9 fixes

---

scripts/eloot.lic
scripts/eloot.ui

v1.4.19
- fixed looting logic when its flagged as two items with one not wanted (eg. uncommon & clothing). It will pick up the item to prevent valuable items getting left behind
- additional error checking for empty box's in containers
- additional error checking for looting
- added support to use left hand for looting
- added support for users who don't sell with eloot (full container tracking)
- added secondary overflow container
- moved UI check only when loading or setup
v1.1.6 (2022-09-05) UI
- added toggle to prioritize left
- added toggle to turn off full container monitoring to support those not selling with eloot
- added secondary overflow container

Updates to script and UI

---

scripts/bigshot.lic

currently hunting scripts started with arguments (i.e. hunting scripts of: `spellactive,my_hunting_script optional args here,helppeople`) are not properly terminated because the calls to stop all active hunting scripts use the entire entry without splitting on space to account for the args (the script START works as expected). This orphans active scripts that are invoked with arguments as it attempts to `kill_script("my_hunting_script optional args here")` and not `kill_script("my_hunting_script")`

[bigshot.lic] properly kill hunting scripts started with args

---

scripts/CombatLog.lic

Will track damage->target and report on death. Currently tracks fire, barrage, volley, spikethorn, tangleweed, feline companion, flares, rot dot damage, moonbeam. Flares supported are ghezyte, terror, rot, holy fire (doesn't tag damage as holyfire damage, need expanded to track both damage numbers and assign to holy fire. assigns to total damage at this time.) breeze, wild entropy, tailwind, arcane reflex, physical prowess, ensorcell.  Saves to combat_log.yaml

[CombatLog.lic] Creation. Alpha Stage.

---

scripts/repository.lic

remove lich update function ability and point to `;lich5-update` instead.

[repository.lic] v2.40 remove Lich update function

---

scripts/bigshot.lic

Currently bigshot only respects cast rt if you're casting a spell. It immediately tries any other command triggering the game to tell you to wait for your rt. Changed the logic to waitcastrt unless the command doesn't care about cast rt. Like Hide or Cocking your crossbow. Probably are some other commands that will need to be added but I'm unsure what they are.
Made a small change to make bigshot quick respect routines when specified versus only using the quick routine.

[bigshot.lic] waitcastrt? change in def cmd()

---

scripts/bigshot.lic

bearhug was matching on /round(time)?/ causing bigshot to not wait. Removed the extra | as well. Fixed typo in Bearhug cooldown check.

[Bigshot.lic] Typo fixes for cman regex

---

scripts/bigshot.lic

The command checks don't always return true/false. They can return 0 and possibly other results. The only sure thing we have is that if the result is false, it returns false. 
So I changed the returns back to `!= false` from `== true` due to `prone` returns `0` for `true`

[bigshot.lic] v4.13.4 command check tweak

---

scripts/infomon.lic

Updated so ;magic will track 620 properly when it is an element other than nature.
Preventing ;waggle from casting 620 when it's already at max duration.

[Infomon.lic] Updates for 620 tracking

---

scripts/ebounty.lic

v1.0.16 (2022-12-22)
- typo fix for the bugfix for herbalist rooms using UID's

ebounty.lic

---

scripts/bigshot.lic

Bigshot has a wait before moving rooms setting that literally just waits then moves.  Let's make it useful. We enter a room, check for targets, wait the amount of time you set (defaults to .3s), check for targets again, then leaves if no target. Allowing bigshot to handle hidden creatures, creatures walking in, and creatures spawning.
Relocated the pause @WANDER_WAIT outside of the wander proc and added a check for targets.

[Bigshot.lic] Check for targets after wander_wait

---

scripts/bigshot.lic

Change room claim from relying on checkpcs to first pull a buffer when entering the room and looking for Also here:. If nothing is found, then it falls back to checking checkpcs as a backup.  If someone has a claim and they walk out of the room, their claim is removed.

[bigshot.lic] updates to room claim

---

scripts/bigshot.lic

Followers don't need to be told if the room is claimed, the head tells them its ok to attack. Removed the follower stuff from the claim system. cleaned up and simplified the buffer check.
added mstrike lockout message to assault regex.

[bigshot.lic] v4.14.6 fixes: head/tail, cast_signs, mstrike lockout

---

scripts/tdusk.lic

Move turning enhancives off to before pausing between runs due to race condition of not being out of combat

[tdusk.lic] v1.23.10

---

scripts/infomon.lic

Fix premature silence end for psm skills with text after <output class="">
turns:
--- Lich: infomon active.
[infomon: checking Feat...]
H>
[infomon: checking Armor...]
Available Armor Specializations Points: 4
H>
[infomon: checking Weapon...]
H>
[infomon: checking Shield...]
H>
[infomon: checking CMan...]
H>
[infomon: done]
into: 
--- Lich: infomon active.
[infomon: checking Feat...]
[infomon: checking Armor...]
[infomon: checking Weapon...]
[infomon: checking Shield...]
[infomon: checking CMan...]
[infomon: done]

[infomon.lic] update

---

scripts/bigshot.lic

- bugfix to allow cmd_weapons to work if using more than base Mnemonic
- bugfix to allow cmd_shields to work if using more than base Mnemonic
- bugfix to allow cmd_cmans to work if using more than base Mnemonic
- bugfix to allow cmd_bearhug to work if using more than base Mnemonic
- bugfix to allow cmd_rogue_cmans to work if using more than base Mnemonic

[bigshot.lic] v4.15.2 bugfix for various cmds

---

type_data/migrations/44_missing_bundles.rb

`glistening black eye` bundles as a `bundle of black eyes` instead of glistening.

[gameobj] bundle of black eyes

---

scripts/ecleanse.lic

Bugfix for regex comparison of an integer in Ruby 3.2+, force convert .to_s

[ecleanse.lic] v1.0.13 Ruby 3.2 bugfix

---

scripts/spell-list.xml

was missing a comma in the DOTHISTIMEOUT in the cast-proc
```
>;e echo Spell['Sign of Dark'].cast
[exec1]>sign of darkness
Darkness enfolds and surrounds you...
[Council, Misty Void]
You are totally surrounded by dense mist.  All directions are the same, yet all directions hold different possibilities.
Obvious exits: north, northeast, east, southeast, south, southwest, west, northwest, up, down, out
You feel drained!
[exec1: Darkness enfolds and surrounds you...]
```

[spell-list.xml] fix typo for sign of darkness

---

.rubocop.yml

Add Layout/FirstHashElementIndentation EnforcedStyle consistent
Will cause hash elements to be indented properly.
Instead of:
```ruby
@locker_items.push({
:id          => id,
:location_id => location_id.to_i,
:level       => level.to_i,
})
```
We'd get
```ruby
@locker_items.push({
:id          => id,
:location_id => location_id.to_i,
:level       => level.to_i,
})```

[rubocop.yml] add Layout/FirstHashElementIndentation

---

scripts/bigshot.lic

* [Bigshot.lic] Add sneaking support
When you toggle sneaky sneaky checkbox on the hunting tab. Will enable autosneak movement when it arrives at the hunting area. Will disable autosneak movement when it leaves the hunting area. Will hide before changing rooms during hunt, if you are not hidden. Will disable autosneak movement upon exiting bigshot if it was turned on. feel free to change the names .. hah
* Update bigshot.lic
rubocop fixes
* Update bigshot.lic
more rubocop fixes

[Bigshot.lic] Add sneaking support (#2)

---

scripts/eforgery.lic

Noted a couple of these bugs when using eforgery and fixed them, namely, a catch for when the script should manually go to the door or grinder, and when a glyph was missing.
In addition, I have a ClimateWear cloak, and the messaging for interacting with this container is a little different, so I added those success keywords to the you_get and you_put methods.

[eforgery.lic] Fix a couple bugs, and add ClimateWear/pocket messaging support.

---

.github/workflows/rspec_tests.yml

Cancel previous rspec tests if a new test queues before it finishes.

chore: rspec test rename and concurrency cancel

---

scripts/bigshot.lic
scripts/overwatch.lic

1) Relocated followup and tier tracking out of unarmed method and into hunt_monitor. Allowing cohesion across unarmed and psm UCS attacks. 
2) Added command checks for tier1, !tier1, tier2, !tier2, tier3, !tier3 
3) If you are at tier3 when you initiate fury, it will now use your @TIER3 attack instead of only using jab.
Currently, if you are tier3 with a target and initiate fury, it will only use jab. If you are below tier3, it will start with jab (or a followup attack if you have one) and continue to tier you up.
You can specify an attack for fury to override jabs.
`weapon fury punch target` will use punch instead of jab, while still tiering up for follow up attacks. However if you are tier3 when the fury is started, it will use your @TIER3 instead of punch.

[Bigshot.lic] v4.17.4 update UCS

---

scripts/effect-list.xml

Fix `CMan.burst_of_swiftness` and `CMan.surge_of_strength` to be `CMan['burst_of_swiftness']` and `CMan['surge_of_strength']`

[effect-list.xml] fix for CMan ranks

---

scripts/ledger.lic

- fix for lootcap estimate SQL statement
- add ability to pass year, month, character, game to Ledger::Character.estimate_loot_cap

[ledger.lic] v1.3.0 bugfix lootcap

---

scripts/autostart.lic

Use `Infomon.get("society.status")` instead of `Infomon.get("stat.race")` to prevent possible false complete sync

[autostart.lic] v0.59 update Infomon.get check

---

scripts/eloot.lic

Extended fossil charm logic to also work with coins on the ground

[eloot]v1.6.1 - extend support for fossil charm (ground coins)

---

scripts/ecleanse.lic

Bugfix for cman retreat if current target != creature tht caused grounded debuff

[ecleanse.lic] v1.0.15 cman retreat bugfix

---

scripts/bigshot.lic

Update cmd_spell to skip 335 on cooldown
Update cmd_spell to use Spell.force_incant instead of bs_put for incanted spells

[bigshot.lic] v5.1.3 cmd_spell fixes

---

scripts/ledger.lic

Previously if in the bank at the time another players debt was collected it was being tracked as withdrawn form your own account. Also added fix for when you do not have enough to cover the whole fine, without the full fine was being deducted.

Debt collector fixes

---

scripts/ledger.lic

This is intended to be an entirely non-function change, ready for future functional changes, as the regex's were quite hard to work with in previous form. All the old regex's are confirmed matching correctly post change (and majority of them are unchanged anyway).
If there is a better way to do this, let me know. And just for reference reason for this was to make it easier to re-introduce note tracking (currently only works in Terras), thought it made sense to split into two smaller releases for easier review (happy to bundle it all into one though)

[ledger.lic] v1.3.2 code optimization & cleanup

---

scripts/ebounty.lic

bugfix for CLI setting values to true/false with Ruby 3.2

[ebounty.lic] v1.1.26 CLI bugfix

---

scripts/bigshot.lic

Some targets have 115 which can add an additional line between `You gesture` and the resolution line. Added a check for buffer[i + 3] to deal with this.
Added a match to break out of the loop when `Your magic fails to find a target.`

[bigshot.lic] v5.1.6 cmd_force adjustments

---

scripts/ledger.lic

Tracking of BP's was broken during code cleanup in 1.3.2, this restore functionality.

[ledger] v1.3.3 - Bugfix: BP Tracking

---

scripts/gemsort2.lic

Unless I am missing something obvious looks like this var got missed in the code cleanup, main reason I question it is without this fix script does not work at all so maybe under used or everyone fixing locally like I did (until finally getting around to this PR).

[gemstort2] 1.0.4 - Bugfix: Fix variable name

---

scripts/targetwindow.lic

made an adjustment so the flashing box will happen when you change targets and not require the number of targets/status to change to fire it off.

[TargetWindow.lic]v1.2 adjusted annotation occurence

---

scripts/coins.lic
scripts/eherbs.lic
scripts/eloot.lic
scripts/go2.lic
scripts/spa.lic
scripts/uhaul.lic

The output of the wealth command changed today:
https://discord.com/channels/226045346399256576/1121832778791665716/1154365026942070835
I have done a quick search for all EO scripts implementing their own wealth check and update the regex, is a chance I missed some but this should be a good start. I have not been able to test all of the script myself but have tried eherb/eloot and they seem ok and the rest implement in basically the same way.

[Multiple] - Bugfix - Change in Wealth output

---

scripts/targetwindow.lic

Minor addition intended for sorcerers to show the total amount of arms in the room.
Window:
Quick:
Honestly not sure if I like how it looks in the quick bar, but I guess it is also optional.
Also as mentioned if you don't want these changes no pressure to accept them, as the Sorcerer I liked the removal of the spam of arms but still like to know how many I have left.

[TargetWindow.lic] v1.3 - Arm Count

---

scripts/ledger.lic

This feature adds tracking of withdrawing notes from the bank, previously this only worked on Terras where gameline includes value of note withdraw:
`The teller nods and says, "Let's see... that's a scrip for 101 silvers, with a 0 silver fee for the scrip. `
In other towns the value is not shown:
`The teller purses her lips and says, "Hmm, we will have to give you a City-States promissory note for that amount."  The teller makes some marks on a blank note and hands it to you, saying "That is a 0 silver surcharge.  Have a nice day."`
This change enables the XML feed to get the ID of note being passed to you and uses `Lich::Util::quiet_command_xml` to read the note and extract the value. Known issue with this approach is if 2 or more notes are withdrawn before the first note can be read …

[ledger.lic] v1.3.4 note tracking

---

scripts/overwatch.lic

Added a check to see if target re-hid on events that could be a silent strike. Not adding to GameObj if a hide was successfully detected after an attack.

[OverWatch.lic] silent strike update

---

scripts/bigshot.lic

there was an unintended 0.5 second wait in follower.all_present? causing bs_wander to add that to its wait between rooms

[bigshot] v5.2.2 bugfix in bs_wander

---

scripts/eloot.lic

Occasionally the locksmith will not recognize a box. Maybe this is just in Shattered though.
glance
You glance down to see a gilded carved modwir case decorated with bits of colorful glass in your right hand and nothing in your left hand.
>open my case
It appears to be locked.
>pull keys
You pull on the tree of keys, causing an enormous racket!

[eloot] v1.6.13 stow box instead of exiting when unknown response at locksmith

---

scripts/eherbs.lic

updated `EHerbs.data[:potions]` to `EHerbs.data[:use_potions]` so it properly prioritizes potions when the checkbox is selected.

[eherbs.lic] v2.0.3 correct typo on variable

---

scripts/vars.lic

Adds the ability to set vars to true/false booleans as previously it would store it as a string instead of actual TrueClass and FalseClass. Fixes and resolves #1314

[vars.lic] v1.2.0 add boolean support

---

scripts/ebounty.lic

It's probably far and few between, but at least in the atoll there is a forage bounty for seaweed that has you on the log which is nomagic. If using 506 this causes you to cast and fail, cast and fail, then forage. Decided to see about implementing the nomagic tag that Xanlin added to the mapdb. 
Feel free to change any of this as I'm probably not considering everything here. Not sure I got all the casting either.
Adding a check for `Map.current.tags.include?("meta:nomagic")` when casting spells.

[Ebounty.lic] v1.1.35

---

scripts/repository.lic

change effect-list.xml to be updatable on fresh installs by default as required for core functionality

[repository.lic] v2.49 effect-list.xml default updatable

---

scripts/foreach.lic

During a recent refactor the regex capture group for the main filter (m=blah, n=blah, etc.) was changed from match[2] to match[1]. This breaks the logic and makes all filters default to a TYPE filter.
Link to previous versions of script using the [2] match group (first group is either NIL or the conditional skip/first/etc. extra filters)
https://github.com/elanthia-online/scripts/blob/a836db6f0c295a0934297f02d035c3a21d2998c7/scripts/foreach.lic#L1689

[foreach.lic] correct filter regex capture groups

---

scripts/ebestiary.lic

```ruby
>;ebest refresh
--- Lich: ebestiary active.
Updating local cache of creature list from wiki (last updated: 2024-01-25 09:59:56 -0600)...
[ebestiary: Building cache by level...]
[ebestiary: level 10]
[ebestiary: level 20]
[ebestiary: level 30]
[ebestiary: level 40]
[ebestiary: level 50]
[ebestiary: level 60]
[ebestiary: level 70]
[ebestiary: level 80]
[ebestiary: level 90]
[ebestiary: level 100]
[ebestiary: level 110]
[ebestiary: level 120]
[ebestiary: Done!]
>;ebest 5
--- Lich: ebestiary active.
Loading local cache of creature list from wiki (last updated: 2024-01-25 10:06:46 -0600)
+-------+----------------------+---------------------+----------------------------------------------+
| Level | Creature             | Types               | Wiki Link …
```

[ebestiary.lic] updates for new wiki format

---

scripts/ebounty.lic

When ebounty invokes a gem hoarding script, it needs to wait for the script to finish before proceeding. Also, some gem hoarding scripts will handle selling the gems, so ebounty need to check if the bounty is completed after the hoarding script runs.

[ebounty.lic] 1.2.2 bugfix for gem hoarding scripts that handle selling gems

---

scripts/eloot.lic

fix for Frozen Bramble creatures requiring left hand to be empty in order to loot. Fixes #1456

[eloot.lic] v1.6.22 frozen bramble fix

---

scripts/autostart.lic

Use internal Lich5 update module on Lich > 5.6.2 instead of script

[autostart.lic] v0.61 use Lich5 update module on newer lich

---

scripts/bigshot.lic

Adds additional messaging for when in cooldown and messaging not captured, to error out. Add additional regex completion for whips and pummel as was not matching:
```
With a final snap of your wrist, you sweep your skull-piercer back to the ready, your assault complete.
With a susurration of ghezyte, you give your whip a final flick and return to the ready, your assault complete.
```

[bigshot.lic] v5.3.9 cmd_assault additional regex

---

scripts/map.lic

Reverts elanthia-online/scripts#1556 - complaints of window size / position not saved.  Confirmed prior version 1.3.0 works.  Need to review this a bit more to find out why the size shrinks.  Details in Discord #help and #scripting.

Revert "[map.lic] v1.3.1 - fixes for operation under WSL"

---

scripts/eherbs.lic

ego2 will keep moving while running eherbs, if it gets the chance.  This increases the likelihood of losing an escort.

[eherbs.lic] Pause ego2 if running

---

scripts/eloot.lic

Add additional match for `get_regex` for:
```
[eloot]>ready weapon
You are already holding a glowing runestaff.
```

[eloot.lic] v1.6.33 get_regex update

---

scripts/bigshot.lic

`Spell.cast` logic when a spell supports stancing, forces stancing back to defensive/guarded unless an `@@after_stance` is set. This sets that logic so that if you're hunting in an advanced hunting stance, it will put you back in the prior stance. Should prevent having to use `inc 903` to prevent stancing logic by `Spell.cast`

[bigshot.lic] v5.4.2 cmd_spell stance dancing fix

---

scripts/ebounty.lic

Allow to use ebounty without any Gem/Default settings if used for standalone CLI foraging

[ebounty.lic] v1.3.11 standalone foraging fix

---

scripts/repository.lic

Turns out our Fallen and Plat instances both use the Prime map, always.

[repository.lic] Change DR default settings.

---

scripts/go2.lic

Force pathing for vaalor shortcut to be NIL so that it can not be used unless shortcut setting is enabled.

[go2.lic] v.2.2.4 bugfix gs4 vaalor shortcut

---

scripts/eloot.lic

Fixes a bug with building the hoarding inventory when using a family vault as the container

fix(eloot.lic): v2.1.5 bugfix for hoarding inventory

---

scripts/bigshot.lic

Issue with resting scripts when using partial name. IE eherb instead of eherbs. `Script.running?` is exact regex match. To get around this, we fool the regex search of the name. This should prevent any issue as long as no script named "--------.lic" is running.

[bigshot.lic] v5.8.2 bugfix run_script exact name match

---

scripts/bigshot.lic

Restores original functionality of ensuring that the exact name of the script started is what is used in the Script.paused/running checks, which should prevent accidental matching against other similar named running scripts.

fix(bigshot): v5.8.3 detect run_script name better
